import crypto from "node:crypto";
import { mkdirSync } from "node:fs";
import { unlink } from "node:fs/promises";
import { extname, resolve } from "node:path";
import { Router } from "express";
import multer from "multer";
import { pool } from "../database/pool.js";

const uploadDir=resolve("server/uploads/rcmc-profile"); mkdirSync(uploadDir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(_r,f,done)=>done(null,`${crypto.randomUUID()}${extname(f.originalname).toLowerCase()}`)}),limits:{fileSize:15*1024*1024},fileFilter:(_r,f,done)=>done(null,["application/pdf","image/jpeg","image/png"].includes(f.mimetype))});
const editable=new Set(["DRAFT","ACTION_REQUIRED"]);
const childTables={performance:["rcmc_export_performance","financial_year"],certificates:["rcmc_existing_certificates",null],branches:["rcmc_branches","name"],banks:["rcmc_banks","name"],registrations:["rcmc_industrial_registrations","name"],persons:["rcmc_persons","name"],certifications:["rcmc_certifications","name"],products:["rcmc_products","name"],contacts:["rcmc_contacts","name"]};
const countries=["IN|India","BD|Bangladesh","CN|China","IR|Iran","JP|Japan","MV|Maldives","SA|Saudi Arabia","ZA|South Africa","TW|Taiwan","AE|United Arab Emirates","US|United States","GB|United Kingdom","DE|Germany","FR|France","SG|Singapore","AU|Australia","CA|Canada","NL|Netherlands","IT|Italy","ES|Spain"].map(x=>{const [code,name]=x.split("|");return{code,name};});
const epcs=[{code:"GENERAL",name:"Federation of Indian Export Organisations",offices:[{code:"HO",name:"Head Office",address:"New Delhi",region:"National",email:"rcmc@fieo.org",telephone:"",jurisdiction:"All India"}]},{code:"EEPC",name:"Engineering Export Promotion Council",offices:[{code:"WR",name:"Western Regional Office",address:"Mumbai, Maharashtra",region:"West",email:"",telephone:"",jurisdiction:"Western India"},{code:"HO",name:"Head Office",address:"Kolkata, West Bengal",region:"National",email:"",telephone:"",jurisdiction:"All India"}]}];
const sectors=["Engineering Products","Textiles and Apparel","Chemicals","Pharmaceuticals","Agriculture and Food","Gems and Jewellery","Services","Electronics","Leather Products","Marine Products"];
const code=()=>`DRAFTRCMC${Date.now().toString().slice(-9)}`;
async function owned(id,userId){const r=await pool.query("SELECT * FROM rcmc_applications WHERE id=$1 AND user_id=$2",[id,userId]);if(!r.rows[0])throw Object.assign(new Error("RCMC application not found"),{status:404});return r.rows[0];}
async function full(app){const entries=await Promise.all(Object.entries(childTables).map(async([key,[table]])=>[key,(await pool.query(`SELECT * FROM ${table} WHERE application_id=$1 ORDER BY id`,[app.id])).rows]));const [countryRows,attachments,history]=await Promise.all([pool.query("SELECT * FROM rcmc_countries WHERE application_id=$1 ORDER BY country_name",[app.id]),pool.query("SELECT id,attachment_type,remark,original_name,mime_type,size_bytes,uploaded_at FROM rcmc_attachments WHERE application_id=$1 ORDER BY id",[app.id]),pool.query("SELECT * FROM rcmc_status_history WHERE application_id=$1 ORDER BY created_at DESC",[app.id])]);return{...app,...Object.fromEntries(entries),countries:countryRows.rows,attachments:attachments.rows,history:history.rows};}
async function defaults(userId){const [profile,iec]=await Promise.all([pool.query("SELECT data FROM company_profiles WHERE user_id=$1",[userId]),pool.query("SELECT firm_details,registered_address,bank_details,iec_number FROM iec_applications WHERE user_id=$1 ORDER BY updated_at DESC LIMIT 1",[userId])]);const p=profile.rows[0]?.data||{},i=iec.rows[0]||{};return{basic_details:{iec:i.iec_number||p.iecNumber||"",pan:i.firm_details?.pan||p.panNumber||"",firmName:i.firm_details?.firmName||p.companyName||"",incorporationDate:i.firm_details?.birthDate||p.dateOfIncorporation||"",iecIssuanceDate:p.iecIssuedAt||"",dgftOffice:i.registered_address?.dgftOffice||"",nature:i.firm_details?.nature||p.concernNature||"",exporterCategory:i.firm_details?.exporterCategory||p.exporterImporterCategory||"",cin:i.firm_details?.cin||p.incorporationCertificateNo||"",annualTurnover:""},firm_details:{address1:i.registered_address?.address1||p.headOfficeAddress||"",address2:i.registered_address?.address2||"",city:i.registered_address?.city||"",pincode:i.registered_address?.pincode||"",district:i.registered_address?.district||"",state:i.registered_address?.state||""},bank:i.bank_details||{}};}
export function createRcmcProfileRouter({requireAuth,requireRole}){const r=Router();void requireRole;r.use(requireAuth,async(q,res,next)=>{try{if(q.user.role==="CLIENT"){if(q.method!=="GET")return res.status(403).json({message:"Statutory Profile is managed by the Admin and is read-only for clients"});return next();}if(q.user.role!=="ADMIN")return res.status(403).json({message:"Statutory Profile access denied"});const clientId=Number(q.headers["x-statutory-client-id"]||q.query.clientId||q.body?.clientId);if(!clientId)return res.status(422).json({message:"Select a client by CDCR ID first"});const owner=await pool.query("SELECT u.*,'CLIENT'::text AS role FROM users u JOIN roles role ON role.id=u.role_id WHERE u.id=$1 AND role.name='CLIENT'",[clientId]);if(!owner.rows[0])return res.status(404).json({message:"Selected client was not found"});q.statutoryAdmin=q.user;q.user=owner.rows[0];next();}catch(e){next(e);}});
 r.get("/masters",async(_q,res,next)=>{try{const fees=(await pool.query("SELECT epc_code,application_type,membership_years,base_fee,gst_rate FROM rcmc_fee_rules WHERE is_active=TRUE ORDER BY id")).rows;res.json({epcs,sectors,countries,financialYears:["2026-27","2025-26","2024-25","2023-24"],membershipPeriods:[1,2,3,5],starRatings:["NA","One Star","Two Star","Three Star","Four Star","Five Star"],fees});}catch(e){next(e);}});
 r.get("/",async(q,res,next)=>{try{res.json({applications:(await pool.query("SELECT * FROM rcmc_applications WHERE user_id=$1 ORDER BY updated_at DESC",[q.user.id])).rows});}catch(e){next(e);}});
 r.post("/",async(q,res,next)=>{try{const d=await defaults(q.user.id),type=q.body.applicationType==="RENEWAL"?"RENEWAL":"NEW";const x=await pool.query("INSERT INTO rcmc_applications(application_number,user_id,application_type,basic_details,firm_details) VALUES($1,$2,$3,$4,$5) RETURNING *",[code(),q.user.id,type,d.basic_details,d.firm_details]);await pool.query("INSERT INTO rcmc_status_history(application_id,status,event_type,actor_id) VALUES($1,'DRAFT','CREATED',$2)",[x.rows[0].id,q.user.id]);if(d.bank.accountNumber)await pool.query("INSERT INTO rcmc_banks(application_id,name,details) VALUES($1,$2,$3)",[x.rows[0].id,d.bank.bankName||"Primary bank",d.bank]);res.status(201).json({application:await full(x.rows[0])});}catch(e){next(e);}});
 r.get("/:id",async(q,res,next)=>{try{res.json({application:await full(await owned(q.params.id,q.user.id))});}catch(e){next(e);}});
 r.patch("/:id",async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id);if(!editable.has(app.status))return res.status(409).json({message:"Submitted RCMC applications are read-only"});const allowed=["application_type","file_name","basic_details","firm_details","status_holder","preferred_sector","application_details","epc_details","profile_details","fee_details","esign_details","current_step"],sets=[],vals=[];for(const k of allowed)if(q.body[k]!==undefined){vals.push(q.body[k]);sets.push(`${k}=$${vals.length}`);}vals.push(app.id,q.user.id);const x=await pool.query(`UPDATE rcmc_applications SET ${sets.length?sets.join(","):"updated_at=updated_at"},updated_at=NOW() WHERE id=$${vals.length-1} AND user_id=$${vals.length} RETURNING *`,vals);res.json({application:await full(x.rows[0])});}catch(e){next(e);}});
 for(const [path,[table,key]] of Object.entries(childTables)){r.post(`/:id/${path}`,async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id);if(!editable.has(app.status))return res.status(409).json({message:"Application is read-only"});let x;if(path==="performance")x=await pool.query(`INSERT INTO ${table}(application_id,financial_year,direct_exports,deemed_exports,service_exports) VALUES($1,$2,$3,$4,$5) RETURNING *`,[app.id,q.body.financial_year,q.body.direct_exports||0,q.body.deemed_exports||0,q.body.service_exports||0]);else if(key)x=await pool.query(`INSERT INTO ${table}(application_id,${key},details) VALUES($1,$2,$3) RETURNING *`,[app.id,q.body[key]||q.body.name||"Record",q.body.details||{}]);else x=await pool.query(`INSERT INTO ${table}(application_id,details) VALUES($1,$2) RETURNING *`,[app.id,q.body.details||{}]);res.status(201).json({item:x.rows[0]});}catch(e){next(e);}});r.delete(`/:id/${path}/:itemId`,async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id);if(!editable.has(app.status))return res.status(409).json({message:"Application is read-only"});await pool.query(`DELETE FROM ${table} WHERE id=$1 AND application_id=$2`,[q.params.itemId,app.id]);res.status(204).end();}catch(e){next(e);}});}
 r.put("/:id/countries",async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id);if(!editable.has(app.status))return res.status(409).json({message:"Application is read-only"});await pool.query("DELETE FROM rcmc_countries WHERE application_id=$1",[app.id]);for(const c of q.body.countries||[])await pool.query("INSERT INTO rcmc_countries(application_id,country_code,country_name) VALUES($1,$2,$3)",[app.id,c.code,c.name]);res.json({countries:(await full(app)).countries});}catch(e){next(e);}});
 r.post("/:id/attachments",upload.single("file"),async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id);if(!editable.has(app.status))return res.status(409).json({message:"Application is read-only"});if(!q.file)return res.status(422).json({message:"PDF, JPG or PNG file required"});const x=await pool.query("INSERT INTO rcmc_attachments(application_id,attachment_type,remark,original_name,stored_name,mime_type,size_bytes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,attachment_type,remark,original_name,mime_type,size_bytes,uploaded_at",[app.id,q.body.attachmentType||"Supporting Document",q.body.remark||"",q.file.originalname,q.file.filename,q.file.mimetype,q.file.size]);res.status(201).json({attachment:x.rows[0]});}catch(e){next(e);}});
 r.get("/:id/attachments/:attachmentId",async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id),x=await pool.query("SELECT * FROM rcmc_attachments WHERE id=$1 AND application_id=$2",[q.params.attachmentId,app.id]);if(!x.rows[0])return res.status(404).json({message:"Attachment not found"});res.download(resolve(uploadDir,x.rows[0].stored_name),x.rows[0].original_name);}catch(e){next(e);}});
 r.delete("/:id/attachments/:attachmentId",async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id),x=await pool.query("DELETE FROM rcmc_attachments WHERE id=$1 AND application_id=$2 RETURNING stored_name",[q.params.attachmentId,app.id]);if(x.rows[0])await unlink(resolve(uploadDir,x.rows[0].stored_name)).catch(()=>{});res.status(204).end();}catch(e){next(e);}});
 r.post("/:id/quote",async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id),d=q.body,rule=(await pool.query("SELECT * FROM rcmc_fee_rules WHERE epc_code IN ($1,'GENERAL') AND application_type=$2 AND membership_years=$3 AND is_active=TRUE ORDER BY epc_code=$1 DESC LIMIT 1",[d.epcCode||"GENERAL",app.application_type,Number(d.membershipYears||1)])).rows[0];if(!rule)return res.status(422).json({message:"No active fee rule is configured"});const base=Number(rule.base_fee),gst=Number(rule.gst_rate),sameState=Boolean(d.sameState),cgst=sameState?base*gst/200:0,sgst=cgst,igst=sameState?0:base*gst/100;res.json({quote:{baseFee:base,gstRate:gst,cgst,sgst,igst,total:base+cgst+sgst+igst}});}catch(e){next(e);}});
 r.post("/:id/submit",async(q,res,next)=>{try{const app=await owned(q.params.id,q.user.id),b=app.basic_details||{},d=app.application_details||{};const missing=[[b.iec,"IEC"],[b.pan,"PAN"],[b.firmName,"Firm Name"],[d.epcCode,"EPC / Commodity Board"],[d.membershipYears,"Membership Period"],[app.fee_details?.total,"Fee calculation"]].filter(([v])=>!v).map(([,n])=>n);if(missing.length)return res.status(422).json({message:`Complete required fields: ${missing.join(", ")}`});const x=await pool.query("UPDATE rcmc_applications SET status='SUBMITTED',current_step=20,submitted_at=NOW(),updated_at=NOW() WHERE id=$1 RETURNING *",[app.id]);await pool.query("INSERT INTO rcmc_status_history(application_id,status,event_type,comments,actor_id) VALUES($1,'SUBMITTED','SUBMITTED','RCMC application submitted by client',$2)",[app.id,q.user.id]);res.json({application:await full(x.rows[0])});}catch(e){next(e);}});return r;}
