import {
    User,
    Vault,
    Home,
    Store,
    FileText,
    Activity,
    Settings,
    Wallet,
    CreditCard,
    Shield,
    Folder,
    Factory,
    Globe,
    Scale,
    FileCheck,
    Layers,
    Truck,
    Building,
    ClipboardList,
    BarChart,
    ShieldCheck,
    Landmark,
    ScrollText,
    FileBadge2,
} from "lucide-react";

export const iconMap = {
    // 🔹 LEVEL 1
    "/client/command-center": Home,
    "/client/service-store": Store,
    "/client/track-request": FileText,
    "/client/active-workflows": Activity,
    "/client/company-profile": Settings,
    "/client/company-profile-setup": ClipboardList,
    "/company-profile": Settings,
    "/client/wallet-credit": Wallet,
    "/client/invoices-billing": CreditCard,
    "/client/schemes-analytics": BarChart,
    "/client/compliance-audit": ClipboardList,
    "/client/smart-vault": Vault,

    // 🔹 LEVEL 2 (SERVICE STORE)
    "/client/service-store/liquidity": Wallet,
    "/client/service-store/licensing-incentive": Landmark,
    "/client/service-store/customs-portops": Truck,
    "/client/service-store/regulatory-bis": ShieldCheck,
    "/client/service-store/legal-audit": Scale,
    "/client/service-store/compliance": ShieldCheck,
    "/client/service-store/licensing": Landmark,
    "/client/service-store/registration": Building,
    "/client/service-store/incentives": Wallet,
    "/client/service-store/custom-filing": FileText,
    "/client/service-store/dispute-resolution": Shield,
    "/client/service-store/iso-trademark": FileCheck,
    "/client/service-store/logistics": Truck,
    "/client/service-store/compliance/certificate-of-origin": ScrollText,
    "/client/service-store/compliance/iem-registration": Building,
    "/client/service-store/compliance/industrial-licence": Factory,
    "/client/service-store/compliance/industrial-license": Factory,
    "/client/service-store/compliance/wpc-licence": Globe,
    "/client/service-store/compliance/wpc-license": Globe,
    "/client/service-store/compliance/un-iip-certificate": FileCheck,
    "/client/service-store/compliance/gst-return": FileText,
    "/client/service-store/compliance/gst-lut-filing": FileText,
    "/client/service-store/compliance/cdsco-drug-control": FileCheck,
    "/client/service-store/compliance/aqcs-pqms": Shield,
    "/client/service-store/compliance/warehouse-license": Factory,
    "/client/service-store/compliance/warehouse-licence": Factory,
    "/client/service-store/compliance/dsc-services": FileBadge2,
    "/client/service-store/compliance/ebrc": FileBadge2,
    "/client/service-store/compliance/bulk-ebrc": Layers,
    "/client/service-store/compliance/igcr-return": ClipboardList,
    "/client/service-store/compliance/pollution-control": Shield,
    "/client/service-store/compliance/ca-certification": FileCheck,
    "/client/service-store/compliance/lmpc": Scale,
    "/client/service-store/compliance/epr-authorisation": Layers,
    "/client/service-store/compliance/epr-authorization": Layers,
    "/service-store": Store,
    "/service-store/compliance": ShieldCheck,
    "/service-store/licensing": Landmark,
    "/service-store/registration": Building,
    "/service-store/incentives": Wallet,
    "/service-store/custom-filing": FileText,
    "/service-store/dispute-resolution": Shield,
    "/service-store/iso-trademark": FileCheck,
    "/service-store/logistics": Truck,
    "/service-store/compliance/certificate-of-origin": ScrollText,
    "/service-store/compliance/iem-registration": Building,
    "/service-store/compliance/industrial-licence": Factory,
    "/service-store/compliance/industrial-license": Factory,
    "/service-store/compliance/wpc-licence": Globe,
    "/service-store/compliance/wpc-license": Globe,
    "/service-store/compliance/un-iip-certificate": FileCheck,
    "/service-store/compliance/gst-return": FileText,
    "/service-store/compliance/gst-lut-filing": FileText,
    "/service-store/compliance/cdsco-drug-control": FileCheck,
    "/service-store/compliance/aqcs-pqms": Shield,
    "/service-store/compliance/warehouse-license": Factory,
    "/service-store/compliance/warehouse-licence": Factory,
    "/service-store/compliance/dsc-services": FileBadge2,
    "/service-store/compliance/ebrc": FileBadge2,
    "/service-store/compliance/bulk-ebrc": Layers,
    "/service-store/compliance/igcr-return": ClipboardList,
    "/service-store/compliance/pollution-control": Shield,
    "/service-store/compliance/ca-certification": FileCheck,
    "/service-store/compliance/lmpc": Scale,
    "/service-store/compliance/epr-authorisation": Layers,
    "/service-store/compliance/epr-authorization": Layers,

    // 🔹 LEVEL 3 (LIQUIDITY)
    "/client/service-store/igst": FileBadge2,
    "/client/service-store/duty": FileText,
    "/client/service-store/interest": FileText,

    // 🔹 LEVEL 3 (LICENSING)
    "/client/service-store/advance-auth": FileCheck,
    "/client/service-store/epcg": FileCheck,
    "/client/service-store/star": Globe,
    "/client/service-store/rex": Globe,
    "/client/service-store/iec": Building,

    // 🔹 LEVEL 3 (CUSTOMS)
    "/client/service-store/moowr": Factory,
    "/client/service-store/dpd": Truck,
    "/client/service-store/rmcc": Shield,
    "/client/service-store/svb": Shield,
    "/client/service-store/factory-stuffing": Factory,

    // 🔹 LEVEL 3 (REGULATORY)
    "/client/service-store/fssai": FileCheck,
    "/client/service-store/wpc": Globe,
    "/client/service-store/legal-metrology": Scale,
    "/client/service-store/aqcs": Shield,
    "/client/service-store/cdsco": FileCheck,
    "/client/service-store/epr": Layers,
    "/client/service-store/bis": FileCheck,

    // 🔹 LEVEL 3 (LEGAL)
    "/client/service-store/iso": FileCheck,
    "/client/service-store/dgft-relaxation": FileText,
    "/client/service-store/customs-defense": Shield,
    "/client/service-store/ca-certification": FileCheck,

    // 🔹 ADMIN
    "/admin/command-center": Home,
    "/admin/users": User,
    "/admin/menus": Folder,
    "/admin/company-profile": Settings,
    "/clients": Building,
    "/admin/clients": Building,
    "/admin/client-management": Building,
    "/admin/workforce": Shield,
    "/admin/request-board": Activity,
    "/admin/smart-vault": Vault,
    "/admin/wallet-credit": Wallet,
    "/admin/invoice-billing": CreditCard,
    "/admin/compliance-audits": BarChart,

    // Agent
    "/agent/dashboard" : Home,
    "/agent/my-tasks": ClipboardList,
    "/agent/data-entry" : FileText,
    "/agent/conduct-audits" : Shield


};
