import { listFinancialTransactions } from "../models/certificateOfOrigin.model.js";
import { createServiceRequest, deleteServiceDocument, findClientServiceIdentity, findFinancialContext, findServiceDefinition, findServiceDocument, findServiceRequest, listServiceDocuments, listServiceRequests, submitServiceRequestAndDeduct, updateServiceDraft, upsertServiceDocument } from "../models/serviceRequest.model.js";

const SERVICE_SLUG = "bis";
const httpError = (status, message, details) => Object.assign(new Error(message), { status, details });
async function definition() { const value = await findServiceDefinition(SERVICE_SLUG); if (!value) throw httpError(404, "BIS Registration is unavailable"); return value; }
function calculate(config, mode) {
  const pricing = config?.pricing || {};
  const officialFee = Number(pricing.officialFees?.[mode] || 0);
  const draftingFee = Number(pricing.draftingFees?.[mode] || 0);
  const shieldPremium = Number(pricing.shieldPremiums?.[mode] ?? pricing.shieldPremium ?? 0);
  const serviceCharge = Number((draftingFee + shieldPremium).toFixed(2));
  const serviceGstRate = Number(pricing.serviceGstRate || 0);
  const gst = Number((serviceCharge * serviceGstRate / 100).toFixed(2));
  return { currency: config.currency || "INR", officialFee, draftingFee, shieldPremium, serviceCharge, serviceGstRate, gst, total: Number((officialFee + serviceCharge + gst).toFixed(2)) };
}
export async function getBisConfiguration(userId) { const [d, finances, identity] = await Promise.all([definition(), findFinancialContext(userId), findClientServiceIdentity(userId)]); return { service: { slug: d.slug, category: d.category, name: d.name, description: d.description, ...d.config }, identity: { iecNumber: identity.iec_number, gstin: identity.gstin, companyName: identity.company_name }, financialContext: { walletBalance: Number(finances.wallet_balance || 0), creditLineBalance: Number(finances.credit_line_balance || 0), creditLimit: Number(finances.credit_limit || 0) } }; }
export async function getBisQuote(userId, mode) { const { service, financialContext } = await getBisConfiguration(userId); const quote = calculate(service, mode); return { ...quote, openingWalletBalance: financialContext.walletBalance, closingWalletBalance: Number((financialContext.walletBalance - quote.officialFee).toFixed(2)), currentCreditLimit: financialContext.creditLineBalance, availableCreditAfter: Number((financialContext.creditLineBalance - quote.serviceCharge - quote.gst).toFixed(2)) }; }
export async function saveBisDraft(userId, payload) { const pricingSnapshot = await getBisQuote(userId, payload.requestMode); if (!payload.requestId) return createServiceRequest({ userId, serviceSlug: SERVICE_SLUG, payload, pricingSnapshot }); const current = await findServiceRequest(payload.requestId, userId, SERVICE_SLUG); if (!current) throw httpError(404, "BIS draft not found"); if (current.status !== "DRAFT") throw httpError(409, "Submitted requests can no longer be edited"); return updateServiceDraft({ requestId: payload.requestId, userId, serviceSlug: SERVICE_SLUG, payload, pricingSnapshot }); }
export async function submitBis(userId, payload) { const [d, pricingSnapshot] = await Promise.all([definition(), getBisQuote(userId, payload.requestMode)]); if (!payload.requestId) throw httpError(422, "Save the BIS request before submitting it"); const uploaded = await listServiceDocuments(payload.requestId, userId, SERVICE_SLUG); const keys = new Set(uploaded.map((item) => item.document_key)); const missing = (d.config?.documents || []).filter((item) => (item.required || item.requiredFor?.includes(payload.requestMode)) && !keys.has(item.id)); if (missing.length) throw httpError(422, "Upload all required BIS documents", { documents: missing.map((item) => item.id) }); const verifiedPayload = { ...payload, manufacturingSite: payload.requestMode === "FMCS" ? "Foreign Manufacturing Site" : "Domestic / SEZ Manufacturing Site", documents: Object.fromEntries(uploaded.map((item) => [item.document_key, { status: "Uploaded", name: item.original_name }])) }; try { return await submitServiceRequestAndDeduct({ userId, requestId: payload.requestId, serviceSlug: SERVICE_SLUG, payload: verifiedPayload, pricingSnapshot, serviceName: d.name }); } catch (error) { if (error.code?.startsWith("INSUFFICIENT_")) throw httpError(402, "Available balance is insufficient", { code: error.code, ...error.balanceDetails }); if (error.code === "REQUEST_NOT_EDITABLE") throw httpError(409, error.message); throw error; } }
export const getBisRequests = (userId) => listServiceRequests(userId, SERVICE_SLUG);
export async function getBisLedger(userId) { const [finances, transactions] = await Promise.all([findFinancialContext(userId), listFinancialTransactions(userId)]); return { balances: { walletBalance: Number(finances.wallet_balance || 0), creditLineBalance: Number(finances.credit_line_balance || 0), creditLimit: Number(finances.credit_limit || 0) }, transactions: transactions.map((item) => ({ id: item.id, accountType: item.account_type, transactionType: item.transaction_type, amount: Number(item.amount), balanceAfter: Number(item.balance_after), description: item.description, status: item.status, transactionDate: item.created_at, requestCode: item.request_code, serviceName: item.service_name })) }; }
export async function storeBisDocument({ userId, requestId, documentKey, file }) { const [request, d] = await Promise.all([findServiceRequest(requestId, userId, SERVICE_SLUG), definition()]); if (!request) throw httpError(404, "BIS draft not found"); if (request.status !== "DRAFT") throw httpError(409, "Documents cannot be changed after submission"); if (!d.config?.documents?.some((item) => item.id === documentKey)) throw httpError(400, "Unknown BIS document type"); const previous = await findServiceDocument(requestId, documentKey, userId, SERVICE_SLUG); const document = await upsertServiceDocument({ requestId, documentKey, originalName: file.originalname, storedName: file.filename, mimeType: file.mimetype, size: file.size }); return { document, previousStoredName: previous?.stored_name || null }; }
export const getBisDocument = (userId, requestId, key) => findServiceDocument(requestId, key, userId, SERVICE_SLUG);
export const removeBisDocument = (userId, requestId, key) => deleteServiceDocument(requestId, key, userId, SERVICE_SLUG);
