import { createServiceRequest, deleteServiceDocument, findClientServiceIdentity, findFinancialContext, findServiceDefinition, findServiceDocument, findServiceRequest, listServiceDocuments, listServiceRequests, submitServiceRequestAndDeduct, updateServiceDraft, upsertServiceDocument } from "../models/serviceRequest.model.js";
import { listFinancialTransactions } from "../models/certificateOfOrigin.model.js";
const SLUG = "ca-certification";
const httpError = (status, message, details) => Object.assign(new Error(message), { status, details });
async function definition(){const value=await findServiceDefinition(SLUG);if(!value)throw httpError(404,"CA Certification service is unavailable");return value;}
function calculate(config, certificationType){const type=config.pricing?.certificationTypes?.[certificationType];if(!type)throw httpError(400,"CA Certification pricing is unavailable");const officialFee=Number(config.pricing.officialFee||0);const professionalFee=Number(type.professionalFee||0);const shieldPremium=Number(config.pricing.shieldPremium||0);const serviceCharge=professionalFee+shieldPremium;const gstRate=Number(config.pricing.gstRate||0);const gst=Number((serviceCharge*gstRate/100).toFixed(2));return{currency:config.currency||"INR",officialFee,professionalFee,shieldPremium,serviceCharge,gstRate,gst,total:Number((officialFee+serviceCharge+gst).toFixed(2))};}
export async function getCaCertificationConfiguration(userId){const[d,finances,identity]=await Promise.all([definition(),findFinancialContext(userId),findClientServiceIdentity(userId)]);return{service:{slug:d.slug,category:d.category,name:d.name,description:d.description,...d.config},clientContext:{iecNumber:identity.iec_number,gstin:identity.gstin,companyName:identity.company_name},financialContext:{walletBalance:Number(finances.wallet_balance||0),creditLineBalance:Number(finances.credit_line_balance||0),creditLimit:Number(finances.credit_limit||0)}};}
export async function getCaCertificationQuote(userId,input){const{service,financialContext}=await getCaCertificationConfiguration(userId);const quote=calculate(service,input.certificationType);return{...quote,openingWalletBalance:financialContext.walletBalance,closingWalletBalance:Number((financialContext.walletBalance-quote.officialFee).toFixed(2)),currentCreditLimit:financialContext.creditLineBalance,availableCreditAfter:Number((financialContext.creditLineBalance-quote.serviceCharge-quote.gst).toFixed(2))};}
export async function saveCaCertificationDraft(userId,payload){const pricingSnapshot=await getCaCertificationQuote(userId,payload);if(!payload.requestId)return createServiceRequest({userId,serviceSlug:SLUG,payload,pricingSnapshot});const current=await findServiceRequest(payload.requestId,userId,SLUG);if(!current)throw httpError(404,"CA Certification draft not found");if(current.status!=="DRAFT")throw httpError(409,"Submitted requests can no longer be edited");return updateServiceDraft({requestId:payload.requestId,userId,serviceSlug:SLUG,payload,pricingSnapshot});}
export async function submitCaCertification(userId,payload){const[d,pricingSnapshot]=await Promise.all([definition(),getCaCertificationQuote(userId,payload)]);if(!payload.requestId)throw httpError(422,"Save the CA Certification request before submitting it");const uploaded=await listServiceDocuments(payload.requestId,userId,SLUG);const keys=new Set(uploaded.map(x=>x.document_key));const missing=(d.config.documents||[]).filter(x=>x.required&&(!x.certificationTypes||x.certificationTypes.includes(payload.certificationType))&&!keys.has(x.id));if(missing.length)throw httpError(422,"Upload all required CA audit evidence",{documents:missing.map(x=>x.id)});const verified={...payload,documents:Object.fromEntries(uploaded.map(x=>[x.document_key,{status:"Uploaded",name:x.original_name}]))};try{return await submitServiceRequestAndDeduct({userId,requestId:payload.requestId,serviceSlug:SLUG,payload:verified,pricingSnapshot,serviceName:d.name});}catch(error){if(error.code?.startsWith("INSUFFICIENT_"))throw httpError(402,"Available balance is insufficient",{code:error.code,...error.balanceDetails});if(error.code==="REQUEST_NOT_EDITABLE")throw httpError(409,error.message);throw error;}}
export const getCaCertificationRequests=userId=>listServiceRequests(userId,SLUG);
export async function getCaCertificationLedger(userId){const[f,t]=await Promise.all([findFinancialContext(userId),listFinancialTransactions(userId)]);return{balances:{walletBalance:Number(f.wallet_balance||0),creditLineBalance:Number(f.credit_line_balance||0),creditLimit:Number(f.credit_limit||0)},transactions:t.map(x=>({id:x.id,accountType:x.account_type,transactionType:x.transaction_type,amount:Number(x.amount),balanceAfter:Number(x.balance_after),description:x.description,status:x.status,transactionDate:x.created_at,requestCode:x.request_code,serviceName:x.service_name}))};}
export async function storeCaCertificationDocument({userId,requestId,documentKey,file}){const[request,d]=await Promise.all([findServiceRequest(requestId,userId,SLUG),definition()]);if(!request)throw httpError(404,"CA Certification draft not found");if(request.status!=="DRAFT")throw httpError(409,"Documents cannot be changed after submission");if(!d.config.documents?.some(x=>x.id===documentKey))throw httpError(400,"Unknown CA Certification document type");const previous=await findServiceDocument(requestId,documentKey,userId,SLUG);const document=await upsertServiceDocument({requestId,documentKey,originalName:file.originalname,storedName:file.filename,mimeType:file.mimetype,size:file.size});return{document,previousStoredName:previous?.stored_name||null};}
export const getCaCertificationDocument=(userId,requestId,key)=>findServiceDocument(requestId,key,userId,SLUG);
export const removeCaCertificationDocument=(userId,requestId,key)=>deleteServiceDocument(requestId,key,userId,SLUG);
