import { createServiceRequest, deleteServiceDocument, findClientServiceIdentity, findFinancialContext, findServiceDefinition, findServiceDocument, findServiceRequest, listServiceDocuments, listServiceRequests, submitServiceRequestAndDeduct, updateServiceDraft, upsertServiceDocument } from "../models/serviceRequest.model.js";
import { listFinancialTransactions } from "../models/certificateOfOrigin.model.js";

const SERVICE_SLUG = "fssai";
const httpError = (status, message, details) => Object.assign(new Error(message), { status, details });
async function getDefinition() { const value = await findServiceDefinition(SERVICE_SLUG); if (!value) throw httpError(404, "FSSAI service is unavailable"); return value; }
function calculate(config, requestMode) { const pricing = config?.pricing || {}; const baseOfficial = Number(pricing.officialFees?.[requestMode] || 0); const officialGstRate = Number(pricing.officialGstRate || 0); const officialGst = Number((baseOfficial * officialGstRate / 100).toFixed(2)); const officialFee = Number((baseOfficial + officialGst).toFixed(2)); const draftingFee = Number(pricing.serviceFees?.[requestMode] || 0); const serviceGstRate = Number(pricing.serviceGstRate || 0); const gst = Number((draftingFee * serviceGstRate / 100).toFixed(2)); return { currency: config.currency || "INR", baseOfficial, officialGstRate, officialGst, officialFee, draftingFee, serviceCharge: draftingFee, serviceGstRate, gst, total: Number((officialFee + draftingFee + gst).toFixed(2)) }; }
function applies(document, payload) { return (!document.modes || document.modes.includes(payload.requestMode)) && (!document.licenseTypes || document.licenseTypes.includes(payload.licenseType)) && (!document.licenseRoles || document.licenseRoles.includes(payload.licenseRole)); }
export async function getFssaiConfiguration(userId) { const [definition, finances, identity] = await Promise.all([getDefinition(), findFinancialContext(userId), findClientServiceIdentity(userId)]); return { service: { slug: definition.slug, category: definition.category, name: definition.name, description: definition.description, ...definition.config }, identity: { iecNumber: identity.iec_number, gstin: identity.gstin, companyName: identity.company_name }, financialContext: { walletBalance: Number(finances.wallet_balance || 0), creditLineBalance: Number(finances.credit_line_balance || 0), creditLimit: Number(finances.credit_limit || 0) } }; }
export async function getFssaiQuote(userId, requestMode) { const { service, financialContext } = await getFssaiConfiguration(userId); const quote = calculate(service, requestMode); return { ...quote, openingWalletBalance: financialContext.walletBalance, closingWalletBalance: Number((financialContext.walletBalance - quote.officialFee).toFixed(2)), currentCreditLimit: financialContext.creditLineBalance, availableCreditAfter: Number((financialContext.creditLineBalance - quote.serviceCharge - quote.gst).toFixed(2)) }; }
export async function saveFssaiDraft(userId, payload) { const pricingSnapshot = await getFssaiQuote(userId, payload.requestMode); if (!payload.requestId) return createServiceRequest({ userId, serviceSlug: SERVICE_SLUG, payload, pricingSnapshot }); const current = await findServiceRequest(payload.requestId, userId, SERVICE_SLUG); if (!current) throw httpError(404, "FSSAI draft not found"); if (current.status !== "DRAFT") throw httpError(409, "Submitted requests can no longer be edited"); return updateServiceDraft({ requestId: payload.requestId, userId, serviceSlug: SERVICE_SLUG, payload, pricingSnapshot }); }
export async function submitFssai(userId, payload) { const [definition, pricingSnapshot] = await Promise.all([getDefinition(), getFssaiQuote(userId, payload.requestMode)]); if (!payload.requestId) throw httpError(422, "Save the FSSAI request before submitting it"); const uploaded = await listServiceDocuments(payload.requestId, userId, SERVICE_SLUG); const keys = new Set(uploaded.map((item) => item.document_key)); const missing = (definition.config?.documents || []).filter((item) => item.required && applies(item, payload) && !keys.has(item.id)); if (missing.length) throw httpError(422, "Upload all required FSSAI documents", { documents: missing.map((item) => item.id) }); const verifiedPayload = { ...payload, documents: Object.fromEntries(uploaded.map((item) => [item.document_key, { status: "Uploaded", name: item.original_name }])) }; try { return await submitServiceRequestAndDeduct({ userId, requestId: payload.requestId, serviceSlug: SERVICE_SLUG, payload: verifiedPayload, pricingSnapshot, serviceName: definition.name }); } catch (error) { if (error.code?.startsWith("INSUFFICIENT_")) throw httpError(402, "Available balance is insufficient", { code: error.code, ...error.balanceDetails }); if (error.code === "REQUEST_NOT_EDITABLE") throw httpError(409, error.message); throw error; } }
export const getFssaiRequests = (userId) => listServiceRequests(userId, SERVICE_SLUG);
export async function getFssaiLedger(userId) { const [finances, transactions] = await Promise.all([findFinancialContext(userId), listFinancialTransactions(userId)]); return { balances: { walletBalance: Number(finances.wallet_balance || 0), creditLineBalance: Number(finances.credit_line_balance || 0), creditLimit: Number(finances.credit_limit || 0) }, transactions: transactions.map((item) => ({ id: item.id, accountType: item.account_type, transactionType: item.transaction_type, amount: Number(item.amount), balanceAfter: Number(item.balance_after), description: item.description, status: item.status, transactionDate: item.created_at, requestCode: item.request_code, serviceName: item.service_name })) }; }
export async function storeFssaiDocument({ userId, requestId, documentKey, file }) { const [request, definition] = await Promise.all([findServiceRequest(requestId, userId, SERVICE_SLUG), getDefinition()]); if (!request) throw httpError(404, "FSSAI draft not found"); if (request.status !== "DRAFT") throw httpError(409, "Documents cannot be changed after submission"); if (!definition.config?.documents?.some((item) => item.id === documentKey)) throw httpError(400, "Unknown FSSAI document type"); const previous = await findServiceDocument(requestId, documentKey, userId, SERVICE_SLUG); const document = await upsertServiceDocument({ requestId, documentKey, originalName: file.originalname, storedName: file.filename, mimeType: file.mimetype, size: file.size }); return { document, previousStoredName: previous?.stored_name || null }; }
export const getFssaiDocument = (userId, requestId, documentKey) => findServiceDocument(requestId, documentKey, userId, SERVICE_SLUG);
export const removeFssaiDocument = (userId, requestId, documentKey) => deleteServiceDocument(requestId, documentKey, userId, SERVICE_SLUG);
