import {
  createServiceRequest, deleteServiceDocument, findClientServiceIdentity, findFinancialContext,
  findServiceDefinition, findServiceDocument, findServiceRequest, listServiceDocuments,
  listServiceRequests, submitServiceRequestAndDeduct, submitServiceRequestForQuote,
  updateServiceDraft, upsertServiceDocument,
} from "../models/serviceRequest.model.js";
import { listFinancialTransactions } from "../models/certificateOfOrigin.model.js";

const slugs = new Set(["advance-authorisation", "dfia-license", "eop-extension", "scomet-licensing", "customs-license", "fertiliser-import"]);
const error = (status, message, details) => Object.assign(new Error(message), { status, details });
const number = value => Math.max(0, Number(value) || 0);
const visible = (item, form) => !item.visibleWhen || String(form[item.visibleWhen.field]) === String(item.visibleWhen.equals);
async function definition(slug) { if (!slugs.has(slug)) throw error(404, "Licensing service is unavailable"); const item = await findServiceDefinition(slug); if (!item) throw error(404, "Licensing service is unavailable"); return item; }
function pricing(slug, form) {
  if (["advance-authorisation", "eop-extension", "customs-license"].includes(slug)) return { currency: "INR", quoteRequired: true, officialFee: 0, serviceCharge: 0, gst: 0, total: 0, message: "Pricing will be confirmed after document and eligibility review." };
  if (slug === "dfia-license") { const transfer = form.dfiaType === "transferability"; const officialFee = transfer ? 5000 : 1000; const draftingFee = transfer ? 12500 : 5000; const successFee = transfer ? +(number(form.dutyValue) * .01).toFixed(2) : 0; const serviceCharge = draftingFee + successFee; const gst = +(serviceCharge * .18).toFixed(2); return { currency:"INR", officialFee,draftingFee,successFee,serviceCharge,gst,total:officialFee+serviceCharge+gst }; }
  if (slug === "scomet-licensing") { const importing = form.tradeDirection === "Import Restricted"; const officialFee=1000,draftingFee=importing?25000:50000,successFee=+(number(form.contractValue)*.01).toFixed(2),serviceCharge=draftingFee+successFee,gst=+(serviceCharge*.18).toFixed(2); return {currency:"INR",officialFee,draftingFee,successFee,serviceCharge,gst,total:officialFee+serviceCharge+gst}; }
  const clearance = form.requestType === "Clearance"; const officialFee=5000,draftingFee=clearance?25000:10000,successFee=+(number(form.consignmentValue)*.01).toFixed(2),serviceCharge=draftingFee+successFee,gst=+(serviceCharge*.18).toFixed(2); return {currency:"INR",officialFee,draftingFee,successFee,serviceCharge,gst,total:officialFee+serviceCharge+gst};
}
function normalize(config, form, identity) { const value = {}; for (const field of config.fields || []) { if (field.readonly && field.id === "iecNumber") value[field.id] = identity.iec_number || ""; else if (form[field.id] != null) value[field.id] = String(form[field.id]).trim(); } return value; }
function ensureComplete(config, form, documents) { const fields = (config.fields || []).filter(field => field.required && visible(field, form) && !form[field.id]); const documentKeys = new Set(documents.map(doc => doc.document_key)); const docs = (config.documents || []).filter(doc => doc.required && visible(doc, form) && !documentKeys.has(doc.id)); if (fields.length || docs.length) throw error(422, "Complete all required service information", { fields: fields.map(item => item.id), documents: docs.map(item => item.id) }); }
export async function getLicensingConfiguration(userId, slug) { const [item, finance, identity] = await Promise.all([definition(slug), findFinancialContext(userId), findClientServiceIdentity(userId)]); return { service:{slug:item.slug,category:item.category,name:item.name,description:item.description,...item.config}, clientContext:{iecNumber:identity.iec_number || "",gstin:identity.gstin || "",companyName:identity.company_name || ""}, financialContext:{walletBalance:number(finance.wallet_balance),creditLineBalance:number(finance.credit_line_balance),creditLimit:number(finance.credit_limit)} }; }
export async function getLicensingQuote(userId, slug, form={}) { const context = await getLicensingConfiguration(userId, slug); const quote = pricing(slug, form); return {...quote, openingWalletBalance:context.financialContext.walletBalance, closingWalletBalance:+(context.financialContext.walletBalance-quote.officialFee).toFixed(2), currentCreditLimit:context.financialContext.creditLineBalance, availableCreditAfter:+(context.financialContext.creditLineBalance-quote.serviceCharge-quote.gst).toFixed(2)}; }
export async function saveLicensingDraft(userId, slug, input) { const [item, identity] = await Promise.all([definition(slug),findClientServiceIdentity(userId)]); const form=normalize(item.config || {},input.form,identity); const payload={form}; const snapshot=pricing(slug,form); if (!input.requestId) return createServiceRequest({userId,serviceSlug:slug,payload,pricingSnapshot:snapshot}); const current=await findServiceRequest(input.requestId,userId,slug); if (!current) throw error(404,"Draft not found"); if (current.status !== "DRAFT") throw error(409,"Submitted requests can no longer be edited"); return updateServiceDraft({requestId:input.requestId,userId,serviceSlug:slug,payload,pricingSnapshot:snapshot}); }
export async function submitLicensingRequest(userId,slug,input) { if (!input.requestId) throw error(422,"Save the request before submitting it"); const [item,identity,documents]=await Promise.all([definition(slug),findClientServiceIdentity(userId),listServiceDocuments(input.requestId,userId,slug)]); const form=normalize(item.config || {},input.form,identity); ensureComplete(item.config || {},form,documents); const snapshot=pricing(slug,form); const payload={form,documents:Object.fromEntries(documents.map(doc=>[doc.document_key,{status:"Uploaded",name:doc.original_name}]))}; try { return snapshot.quoteRequired ? await submitServiceRequestForQuote({userId,requestId:input.requestId,serviceSlug:slug,payload,pricingSnapshot:snapshot}) : await submitServiceRequestAndDeduct({userId,requestId:input.requestId,serviceSlug:slug,payload,pricingSnapshot:snapshot,serviceName:item.name}); } catch (e) { if (e.code?.startsWith("INSUFFICIENT_")) throw error(402,"Available balance is insufficient",{code:e.code,...e.balanceDetails}); throw e; } }
export const getLicensingRequests=(userId,slug)=>listServiceRequests(userId,slug);
export async function getLicensingLedger(userId) { const [finance,transactions]=await Promise.all([findFinancialContext(userId),listFinancialTransactions(userId)]); return {balances:{walletBalance:number(finance.wallet_balance),creditLineBalance:number(finance.credit_line_balance),creditLimit:number(finance.credit_limit)},transactions:transactions.map(item=>({id:item.id,accountType:item.account_type,transactionType:item.transaction_type,amount:number(item.amount),balanceAfter:number(item.balance_after),description:item.description,status:item.status,transactionDate:item.created_at,requestCode:item.request_code,serviceName:item.service_name}))}; }
export async function storeLicensingDocument({userId,slug,requestId,documentKey,file}) { const [request,item]=await Promise.all([findServiceRequest(requestId,userId,slug),definition(slug)]); if (!request) throw error(404,"Draft not found"); if (request.status !== "DRAFT") throw error(409,"Documents cannot be changed after submission"); if (!(item.config?.documents || []).some(doc=>doc.id===documentKey)) throw error(400,"Unknown document type"); const previous=await findServiceDocument(requestId,documentKey,userId,slug); const document=await upsertServiceDocument({requestId,documentKey,originalName:file.originalname,storedName:file.filename,mimeType:file.mimetype,size:file.size}); return {document,previousStoredName:previous?.stored_name}; }
export const getLicensingDocument=(userId,slug,requestId,key)=>findServiceDocument(requestId,key,userId,slug);
export const removeLicensingDocument=(userId,slug,requestId,key)=>deleteServiceDocument(requestId,key,userId,slug);
