import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { AlertTriangle, Anchor, ArrowLeft, ArrowRight, Beef, FileText, Receipt, Save, Sprout, Upload, Wallet, X, Zap } from "lucide-react";
import { getAqcsPqmsConfiguration, getAqcsPqmsLedger, getAqcsPqmsQuote, getAqcsPqmsRequests, removeAqcsPqmsDocument, saveAqcsPqmsDraft, submitAqcsPqms, uploadAqcsPqmsDocument } from "../../services/aqcsPqmsService";

const emptyFile = { status: "Not Uploaded", name: null };
export default function AqcsPqmsWorkflow({ service, onBack }) {
  const navigate=useNavigate(); const [configuration,setConfiguration]=useState(null); const [quote,setQuote]=useState({}); const [ledger,setLedger]=useState({transactions:[]});
  const [requestId,setRequestId]=useState(null); const [draftCode,setDraftCode]=useState(""); const [requestMode,setRequestMode]=useState("PQMS"); const [requestType,setRequestType]=useState("Clearance");
  const [portCode,setPortCode]=useState(""); const [consignmentValue,setConsignmentValue]=useState(""); const [treatmentType,setTreatmentType]=useState("Fumigation"); const [files,setFiles]=useState({});
  const [initializing,setInitializing]=useState(true); const [busy,setBusy]=useState(false); const [uploading,setUploading]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{let active=true;Promise.all([getAqcsPqmsConfiguration(),getAqcsPqmsRequests(),getAqcsPqmsLedger()]).then(async([config,data,ledgerData])=>{const draft=data.requests?.find(x=>x.status==="DRAFT");const p=draft?.payload||{};const mode=p.requestMode||"PQMS",type=p.requestType||"Clearance",value=p.consignmentValue||"";const pricing=await getAqcsPqmsQuote(mode,type,value);if(!active)return;const restored=Object.fromEntries((config.service.documents||[]).map(x=>[x.id,{...emptyFile}]));for(const doc of draft?.documents||[])restored[doc.documentKey]={status:"Uploaded",name:doc.name,size:Number(doc.size||0)};setConfiguration(config);setQuote(pricing);setLedger(ledgerData);setRequestId(draft?.id||null);setDraftCode(draft?.request_code||"");setRequestMode(mode);setRequestType(type);setPortCode(p.portCode||"");setConsignmentValue(value);setTreatmentType(p.treatmentType||"Fumigation");setFiles(restored);}).catch(()=>active&&setError("Unable to load AQCS & PQMS." )).finally(()=>active&&setInitializing(false));return()=>{active=false};},[]);
  useEffect(()=>{if(initializing)return;const timer=setTimeout(()=>getAqcsPqmsQuote(requestMode,requestType,consignmentValue).then(data=>{setQuote(data);setError("");}).catch(()=>setError("Unable to calculate quarantine pricing.")),250);return()=>clearTimeout(timer);},[requestMode,requestType,consignmentValue,initializing]);
  const config=configuration?.service; const documents=useMemo(()=>(config?.documents||[]).filter(x=>(!x.requestModes||x.requestModes.includes(requestMode))&&(!x.requestTypes||x.requestTypes.includes(requestType))),[config,requestMode,requestType]);
  const payload=()=>({requestId,requestMode,requestType,portCode,consignmentValue:Number(consignmentValue||0),treatmentType,documents:files}); const valid=Boolean(portCode.trim()&&Number(consignmentValue)>0&&documents.filter(x=>x.required).every(x=>files[x.id]?.status==="Uploaded"));
  async function ensureDraft(){if(requestId)return requestId;const data=await saveAqcsPqmsDraft(payload());setRequestId(data.request.id);setDraftCode(data.request.request_code);return data.request.id;}
  async function selectFile(key,event){const file=event.target.files?.[0];event.target.value="";if(!file)return;try{setUploading(key);const id=await ensureDraft();const data=await uploadAqcsPqmsDocument(id,key,file);setFiles(c=>({...c,[key]:{status:"Uploaded",name:data.document.name,size:data.document.size}}));}catch(e){Swal.fire("Upload failed",e.response?.data?.message||"The document could not be uploaded.","error");}finally{setUploading("");}}
  async function removeFile(key){try{setUploading(key);await removeAqcsPqmsDocument(requestId,key);setFiles(c=>({...c,[key]:{...emptyFile}}));}catch(e){Swal.fire("Unable to remove document",e.response?.data?.message||"Please try again.","error");}finally{setUploading("");}}
  async function saveDraft(){try{setBusy(true);const data=await saveAqcsPqmsDraft(payload());setRequestId(data.request.id);setDraftCode(data.request.request_code);await Swal.fire({icon:"success",title:"Bio-audit draft saved",text:`${data.request.request_code} can be resumed later.`,confirmButtonColor:"#2952ff"});}catch(e){Swal.fire("Unable to save draft",e.response?.data?.message||"Please try again.","error");}finally{setBusy(false);}}
  async function submit(){if(!valid)return;try{setBusy(true);const data=await submitAqcsPqms(payload());const [pricing,nextLedger]=await Promise.all([getAqcsPqmsQuote(requestMode,requestType,consignmentValue),getAqcsPqmsLedger()]);setQuote(pricing);setLedger(nextLedger);window.dispatchEvent(new CustomEvent("wallet:updated",{detail:{balance:data.balances.walletBalance,creditLine:data.balances.creditLineBalance}}));await Swal.fire({icon:"success",title:"Quarantine request submitted",text:`${data.request.request_code} has been sent to the Admin Request Board.`,confirmButtonColor:"#2952ff"});onBack();}catch(e){if(e.response?.status===402){const code=e.response?.data?.errors?.code;const message=code==="INSUFFICIENT_WALLET"?"Wallet balance is insufficient. Please top up your Wallet.":code==="INSUFFICIENT_CREDIT_LINE"?"Credit Line balance is insufficient. Please top up your Credit Line.":"Wallet and Credit Line balances are insufficient. Please top up both.";const result=await Swal.fire({icon:"warning",title:"Top up required",text:message,showCancelButton:true,confirmButtonText:"Go to Wallet & Credit",confirmButtonColor:"#2952ff"});if(result.isConfirmed)navigate("/client/wallet-credit#add-credit");}else Swal.fire("Unable to submit request",e.response?.data?.message||"Please try again.","error");}finally{setBusy(false);}}
  if(initializing)return <div className="mx-auto max-w-7xl p-6"><div className="min-h-[700px] animate-pulse rounded-[30px] bg-white shadow-lg"/></div>;
  return <div className="min-h-[calc(100vh-7rem)]"><div className="mx-auto max-w-7xl px-4 py-4 lg:px-6">{error&&<div className="mb-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}{draftCode&&<div className="mb-3 flex gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-3 text-blue-900"><Save size={17}/><div><b className="text-xs">Draft {draftCode} restored</b><p className="text-[11px] text-blue-600">Continue your bio-security request.</p></div></div>}
    <div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.08)]"><header className="flex justify-between border-b p-5"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#2952ff] text-white">{requestMode==="AQCS"?<Beef/>:<Sprout/>}</div><div><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Back to Compliance</button><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black uppercase">{requestMode ? `${requestMode} Bio-Security Audit` : service.title}</h1><span className="rounded-full bg-rose-600 px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-white">Perishable</span></div><p className="mt-1 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">{config?.standard}<Zap size={11} className="text-amber-500"/> Demurrage priority</p></div></div><button onClick={onBack}><X className="text-slate-400"/></button></header>
    <div className="grid gap-5 p-5 xl:grid-cols-[minmax(0,1.45fr)_360px]"><div className="space-y-5"><div className="grid gap-2 rounded-2xl bg-slate-100 p-1 md:grid-cols-2">{(config?.requestModes||[]).map(mode=><button key={mode.id} onClick={()=>setRequestMode(mode.id)} className={`rounded-xl px-3 py-3 ${requestMode===mode.id?"border border-blue-200 bg-white text-[#2952ff] shadow-sm":"text-slate-400"}`}><b className="block text-xs uppercase">{mode.label}</b><span className="text-[9px] uppercase">{mode.description}</span></button>)}</div><div className="grid gap-2 rounded-2xl bg-slate-100 p-1 md:grid-cols-2">{(config?.requestTypes||[]).map(type=><button key={type.id} onClick={()=>setRequestType(type.id)} className={`rounded-xl px-3 py-3 ${requestType===type.id?"border border-blue-200 bg-white text-[#2952ff] shadow-sm":"text-slate-400"}`}><b className="block text-xs uppercase">{type.label}</b><span className="text-[9px] uppercase">{type.description}</span></button>)}</div>
    <div className="grid gap-3 md:grid-cols-2"><Field label="Port of Entry"><input maxLength={6} value={portCode} onChange={e=>setPortCode(e.target.value.toUpperCase())} placeholder="e.g. INNSA1"/></Field><Field label="Consignment Value (INR)"><input type="number" min="0" value={consignmentValue} onChange={e=>setConsignmentValue(e.target.value)} placeholder="CIF value"/></Field><Field label="Phyto-treatment Method"><select value={treatmentType} onChange={e=>setTreatmentType(e.target.value)}>{(config?.treatmentMethods||[]).map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></Field></div>
    <div className="flex gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-blue-900"><Anchor size={18}/><p className="text-[11px] font-semibold">{requestMode==="AQCS"?"Health Certificate clauses will be checked against Indian sanitary protocols before portal filing.":`Phytosanitary evidence and ${treatmentType} treatment dates will be cross-checked against shipment records.`}</p></div>
    <div><h2 className="mb-3 flex items-center gap-2 text-[11px] font-black uppercase tracking-[.18em]"><Upload size={14}/> Required bio-evidence</h2><div className="space-y-2">{documents.map(doc=><article key={doc.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3"><FileText className={files[doc.id]?.status==="Uploaded"?"text-emerald-500":"text-slate-400"}/><div className="min-w-0 flex-1"><b className="block text-xs uppercase">{doc.label}{doc.required&&<em className="ml-2 not-italic text-[9px] text-rose-500">REQUIRED</em>}</b><span className={`block truncate text-[10px] ${files[doc.id]?.status==="Uploaded"?"text-emerald-600":"text-slate-400"}`}>{files[doc.id]?.name||"Compliance file required"}</span></div>{files[doc.id]?.status==="Uploaded"&&<button onClick={()=>removeFile(doc.id)} className="text-[10px] font-black uppercase text-rose-500">Remove</button>}<label className="cursor-pointer rounded-lg border bg-slate-50 px-4 py-2 text-[10px] font-black uppercase">{uploading===doc.id?"Uploading...":files[doc.id]?.status==="Uploaded"?"Replace":"Upload"}<input className="sr-only" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e=>selectFile(doc.id,e)}/></label></article>)}</div></div><div className="flex gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-800"><AlertTriangle size={18}/><p className="text-[11px] font-semibold">Certificates containing overwriting or undeclared stamps may be rejected by the Bio-Security portal.</p></div></div>
    <aside className="overflow-hidden rounded-3xl bg-slate-900 text-white shadow-xl xl:sticky xl:top-24 xl:self-start"><div className="flex items-center gap-2 border-b border-white/10 p-5 text-blue-400"><Receipt size={16}/><span className="text-[10px] font-black uppercase tracking-[.2em]">Settlement Ledger</span></div><div className="space-y-5 p-5"><Ledger title="Prepaid Wallet" balance={quote.openingWalletBalance} lines={[["Statutory Testing & Portal Fee",quote.officialFee]]} after={quote.closingWalletBalance}/><Ledger title="Corporate Credit Line" balance={quote.currentCreditLimit} lines={[["Technical Dossier & Coordination",quote.draftingFee],["Bio-Security Shield Premium",quote.successFee],["GST (18%)",quote.gst]]} after={quote.availableCreditAfter}/></div><div className="flex justify-between bg-[#2952ff] p-5"><div><span className="text-[9px] font-black uppercase text-blue-100">Total Audit Debit</span><b className="block text-2xl">₹{Number(quote.total||0).toLocaleString("en-IN")}</b></div><span className="text-right text-[9px] uppercase text-white/70">SLA: {config?.sla}<br/>{ledger.transactions.length} ledger entries</span></div></aside></div>
    <footer className="flex flex-col justify-between gap-3 border-t bg-slate-50 p-5 sm:flex-row"><button onClick={onBack} className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Discard</button><div className="flex gap-3"><button onClick={saveDraft} disabled={busy} className="flex items-center gap-2 rounded-xl border bg-white px-6 py-3 text-sm font-bold"><Save size={16}/> Save Draft</button><button onClick={submit} disabled={busy||!valid} className={`flex items-center gap-2 rounded-xl px-7 py-3 text-sm font-black ${valid?"bg-[#2952ff] text-white":"bg-slate-200 text-slate-400"}`}>{valid?"Confirm & File Audit":"Incomplete Audit"}<ArrowRight size={16}/></button></div></footer></div></div></div>;
}
function Field({label,children}){return <label className="space-y-1.5"><span className="px-1 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">{label}</span><span className="iem-field-control block">{children}</span></label>}
function Ledger({title,balance,lines,after}){return <div><div className="mb-3 flex justify-between text-[10px] font-black uppercase tracking-widest text-slate-500"><span>{title}</span><Wallet size={14}/></div><div className="space-y-2 text-xs"><div className="flex justify-between"><span className="text-slate-400">Opening Balance</span><b>₹{Number(balance||0).toLocaleString("en-IN")}</b></div>{lines.map(([label,amount])=><div key={label} className="flex justify-between border-t border-white/10 pt-2"><span className="text-slate-400">{label}</span><b className="text-rose-400">- ₹{Number(amount||0).toLocaleString("en-IN")}</b></div>)}<div className="flex justify-between border-t border-white/10 pt-2"><span className="text-blue-400">Available Post-Task</span><b>₹{Number(after||0).toLocaleString("en-IN")}</b></div></div></div>}
