import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { Activity, Anchor, ArrowLeft, ArrowRight, CheckCircle2, Download, FileText, Info, LoaderCircle, Receipt, Save, ShieldCheck, Trash2, TrendingUp, Undo2, Upload, X } from "lucide-react";
import { downloadLicensingDocument, getLicensingConfiguration, getLicensingLedger, getLicensingQuote, getLicensingRequests, removeLicensingDocument, saveLicensingDraft, submitLicensingRequest, uploadLicensingDocument } from "../../services/licensingService";

const SLUG="duty-drawback";
const money=value=>new Intl.NumberFormat("en-IN",{maximumFractionDigits:2}).format(Number(value||0));
const errorText=(error,fallback)=>error?.response?.data?.message||error?.message||fallback;
const keyOf=item=>item?.document_key||item?.documentKey||"";
const nameOf=item=>item?.original_name||item?.name||"Uploaded document";
const USAGE=[["0","Unused · 98% Drawback"],["3","Up to 3 Months · 95%"],["6","3–6 Months · 85%"],["12","6–12 Months · 70%"],["24","1–2 Years · 60%"]];

export default function DutyDrawbackWorkflow({onBack}){
 const navigate=useNavigate(),fileInputs=useRef({});
 const[configuration,setConfiguration]=useState(null),[entity,setEntity]=useState({}),[draft,setDraft]=useState(null);
 const[form,setForm]=useState({drawbackType:"Section74",usagePeriod:"0",wastagePercent:"",iecNumber:"",claimValue:"",portCode:"",importBoeNo:"",exportSbNo:""});
 const[documents,setDocuments]=useState([]),[quote,setQuote]=useState(null),[ledger,setLedger]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uploading,setUploading]=useState("");
 useEffect(()=>{let active=true;Promise.all([getLicensingConfiguration(SLUG),getLicensingRequests(SLUG),getLicensingLedger(SLUG)]).then(async([configData,requestData,ledgerData])=>{const restored=requestData.requests?.find(item=>item.status==="DRAFT");const nextForm={drawbackType:"Section74",usagePeriod:"0",wastagePercent:"",iecNumber:configData.clientContext?.iecNumber||"",claimValue:"",portCode:"",importBoeNo:"",exportSbNo:"",...(restored?.payload?.form||{})};const nextQuote=await getLicensingQuote(SLUG,nextForm);if(!active)return;setConfiguration(configData.service);setEntity(configData.clientContext||{});setDraft(restored||null);setForm(nextForm);setDocuments(restored?.documents||[]);setQuote(nextQuote);setLedger(ledgerData)}).catch(error=>Swal.fire("Unable to load Duty Drawback",errorText(error,"Please try again shortly."),"error")).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const documentRules=useMemo(()=>[{id:"dutyPaymentChallan",label:"Import Duty TR6 Challan Copy"},...(form.drawbackType==="Section74"?[{id:"importBoe",label:"Import Bill of Entry · EP Copy"},{id:"exportSb",label:"Export Shipping Bill · EP Copy"},{id:"identityProof",label:"Correlation Evidence · Serial Numbers / Marks"}]:[{id:"annexure1",label:"Annexure 1 · Consumption Matrix"},{id:"annexure2",label:"Annexure 2 · Input Duty Detail Sheet"},{id:"consumptionSheet",label:"Wastage Reconciliation Report"}])],[form.drawbackType]);
 async function updateField(field,value){const next={...form,[field]:value};setForm(next);try{setQuote(await getLicensingQuote(SLUG,next))}catch{setQuote(null)}}
 function validationMessage(){if(!/^[A-Z0-9]{5,10}$/.test(form.portCode))return"Enter a valid 5 to 10 character customs port code.";if(Number(form.claimValue)<=0)return"Enter a valid drawback claim value greater than zero.";if(form.drawbackType==="Section74"&&(form.importBoeNo.trim().length<4||form.exportSbNo.trim().length<4))return"Enter both the Import BOE and Export Shipping Bill numbers.";if(form.drawbackType==="Section75"){const waste=Number(form.wastagePercent);if(form.wastagePercent===""||!Number.isFinite(waste)||waste<=0||waste>100)return"Enter a wastage percentage greater than 0 and up to 100."}const uploaded=new Set(documents.map(keyOf));const missing=documentRules.find(item=>!uploaded.has(item.id));return missing?`Upload the required document: ${missing.label}.`:""}
 async function persistDraft(show=true){const response=await saveLicensingDraft(SLUG,{requestId:draft?.id,form});setDraft(response.request);if(show)await Swal.fire({icon:"success",title:"Drawback draft saved",text:`${response.request.request_code} can be resumed later.`,confirmButtonColor:"#2952ff"});return response.request}
 async function saveDraft(){try{setBusy(true);await persistDraft()}catch(error){Swal.fire("Unable to save drawback draft",errorText(error,"Please try again."),"error")}finally{setBusy(false)}}
 async function uploadDocument(key,event){const file=event.target.files?.[0];event.target.value="";if(!file)return;try{setUploading(key);const request=draft||await persistDraft(false);const response=await uploadLicensingDocument(SLUG,request.id,key,file);setDocuments(current=>[...current.filter(item=>keyOf(item)!==key),response.document])}catch(error){Swal.fire("Upload failed",errorText(error,"The document could not be uploaded."),"error")}finally{setUploading("")}}
 async function removeDocument(key){if(!draft)return;try{setUploading(key);await removeLicensingDocument(SLUG,draft.id,key);setDocuments(current=>current.filter(item=>keyOf(item)!==key))}catch(error){Swal.fire("Unable to remove file",errorText(error,"Please try again."),"error")}finally{setUploading("")}}
 async function downloadDocument(key,name){try{await downloadLicensingDocument(SLUG,draft.id,key,name)}catch(error){Swal.fire("Unable to download file",errorText(error,"Please try again."),"error")}}
 async function submit(){const missing=validationMessage();if(missing)return Swal.fire({icon:"error",title:"Drawback claim is incomplete",text:missing,confirmButtonColor:"#2952ff"});try{setBusy(true);const request=await persistDraft(false);const response=await submitLicensingRequest(SLUG,{requestId:request.id,form});setLedger(await getLicensingLedger(SLUG));window.dispatchEvent(new CustomEvent("wallet:updated",{detail:{balance:response.balances?.walletBalance,creditLine:response.balances?.creditLineBalance}}));await Swal.fire({icon:"success",title:"Drawback claim submitted",text:`${response.request.request_code} has been sent for audit.`,confirmButtonColor:"#2952ff"});onBack()}catch(error){if(error.response?.status===402){const result=await Swal.fire({icon:"warning",title:"Top up required",text:"Your Wallet or Credit Line balance is insufficient.",showCancelButton:true,confirmButtonText:"Go to Wallet & Credit",confirmButtonColor:"#2952ff"});if(result.isConfirmed)navigate("/client/wallet-credit#add-credit")}else Swal.fire("Unable to submit drawback claim",errorText(error,"Please verify the claim details and documents."),"error")}finally{setBusy(false)}}
 if(loading||!configuration)return <div className="flex min-h-[520px] items-center justify-center text-slate-500"><LoaderCircle className="mr-2 animate-spin"/>Loading Duty Drawback…</div>;
 const valid=!validationMessage(),price=quote||{},balances=ledger?.balances||{};
 return <section className="mx-auto max-w-[1370px] animate-in fade-in duration-300"><div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.08)]">
  <header className="flex items-start justify-between border-b px-5 py-5 md:px-7"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#2952ff] text-white shadow-lg shadow-blue-100"><Undo2/></div><div><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/>Back to Service Store</button><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black">Duty Drawback Recovery Audit</h1><span className="rounded-full bg-slate-900 px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-white">Liquidity</span></div><p className="mt-1 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">{draft?.request_code||"Reference generated on save"} · {entity.companyName||"Company"}{form.iecNumber?` · IEC ${form.iecNumber}`:""}</p></div></div><button onClick={onBack} aria-label="Close workflow"><X className="text-slate-400"/></button></header>
  <div className="grid gap-6 p-5 md:p-7 xl:grid-cols-[minmax(0,1.4fr)_360px]"><div className="space-y-6">
   <div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-100 p-1"><Mode active={form.drawbackType==="Section74"} onClick={()=>updateField("drawbackType","Section74")} title="Section 74" subtitle="Re-export · unused or used"/><Mode active={form.drawbackType==="Section75"} onClick={()=>updateField("drawbackType","Section75")} title="Section 75" subtitle="Brand-rate fixation"/></div>
   <div className="grid gap-4 md:grid-cols-2"><Field label="Customs Port Code" icon={<Anchor size={13}/>}><input maxLength={10} value={form.portCode} onChange={e=>updateField("portCode",e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))} placeholder="e.g. INNSA1"/></Field><Field label="Total Drawback Value (INR)" icon={<TrendingUp size={13}/>}><input type="number" min="1" value={form.claimValue} onChange={e=>updateField("claimValue",e.target.value)} placeholder="Estimated claim amount"/></Field>{form.drawbackType==="Section74"?<><Field label="Usage Duration in India" icon={<Activity size={13}/>}><select value={form.usagePeriod} onChange={e=>updateField("usagePeriod",e.target.value)}>{USAGE.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><div><span className="mb-2 block text-[10px] font-black uppercase tracking-[.14em] text-slate-500">Import BOE / Export SB Pair <em className="not-italic text-rose-500">*</em></span><div className="grid grid-cols-2 gap-2"><input className="iem-inline-input" value={form.importBoeNo} onChange={e=>updateField("importBoeNo",e.target.value)} placeholder="BOE Number"/><input className="iem-inline-input" value={form.exportSbNo} onChange={e=>updateField("exportSbNo",e.target.value)} placeholder="SB Number"/></div></div></>:<div className="md:col-span-2"><Field label="Total Process Wastage (%)" icon={<Activity size={13}/>}><input type="number" min="0" max="100" step="0.1" value={form.wastagePercent} onChange={e=>updateField("wastagePercent",e.target.value)} placeholder="e.g. 5.5"/></Field></div>}</div>
   <div className="flex gap-4 rounded-2xl border bg-blue-50 p-4"><div className="rounded-xl bg-white p-3 text-[#2952ff] shadow-sm"><Info size={21}/></div><div><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">Claim audit logic</p><p className="mt-1 text-sm font-semibold text-slate-700">{form.drawbackType==="Section74"?`The imported and re-exported goods must be correlated exactly. Current usage selection indicates a ${price.drawbackRate||0}% drawback rate.`:"Input duties, consumption and process wastage will be reconciled to prepare the Section 75 brand-rate application."}</p></div></div>
   <div><h2 className="mb-3 text-[11px] font-black uppercase tracking-[.18em] text-slate-800">Comprehensive data matrix</h2><div className="space-y-2">{documentRules.map(item=>{const saved=documents.find(doc=>keyOf(doc)===item.id);return <article key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3 hover:border-blue-300"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${saved?"bg-emerald-50 text-emerald-600":"bg-slate-50 text-slate-400"}`}>{saved?<CheckCircle2 size={20}/>:<FileText size={20}/>}</div><div className="min-w-0 flex-1"><b className="block text-xs">{item.label}<em className="ml-2 text-[9px] not-italic uppercase text-rose-500">Required</em></b><span className={`block truncate text-[10px] ${saved?"text-emerald-600":"text-slate-400"}`}>{saved?nameOf(saved):"PDF, DOC, XLS, JPG or PNG · maximum 20 MB"}</span></div>{saved&&<><button onClick={()=>downloadDocument(item.id,nameOf(saved))} className="rounded-lg p-2 text-[#2952ff]" aria-label={`Download ${item.label}`}><Download size={16}/></button><button onClick={()=>removeDocument(item.id)} className="rounded-lg p-2 text-rose-500" aria-label={`Remove ${item.label}`}><Trash2 size={16}/></button></>}<button onClick={()=>fileInputs.current[item.id]?.click()} disabled={Boolean(uploading)} className="rounded-lg border bg-white px-4 py-2 text-[10px] font-black uppercase disabled:opacity-50"><Upload className="mr-1 inline" size={14}/>{uploading===item.id?"Uploading":saved?"Replace":"Upload"}</button><input ref={node=>{fileInputs.current[item.id]=node}} type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={event=>uploadDocument(item.id,event)}/></article>})}</div></div>
   <div className="flex gap-3 rounded-2xl border border-amber-100 bg-amber-50 p-4 text-[10px] font-black uppercase leading-relaxed text-amber-800"><ShieldCheck className="shrink-0" size={18}/><p>{form.drawbackType==="Section74"?"Serial-number or marks correlation is mandatory; substitution may cause rejection.":"Brand-rate claims must reconcile with realized export proceeds and e-BRC data."}</p></div>
  </div><aside className="h-fit overflow-hidden rounded-3xl bg-slate-950 text-white shadow-xl xl:sticky xl:top-24"><div className="flex items-center gap-2 border-b border-white/10 p-5 text-blue-400"><Receipt size={16}/><span className="text-[10px] font-black uppercase tracking-[.2em]">Transaction Ledger</span></div><div className="space-y-4 p-5"><Ledger label="ICEGATE processing fee" value={price.officialFee}/><Ledger label="Technical audit & drafting" value={price.draftingFee}/><Ledger label="Success fee (1%)" value={price.successFee}/><Ledger label="GST (18%)" value={price.gst}/><div className="border-t border-white/10 pt-3 text-xs text-slate-400"><p>Wallet after: <b className="float-right text-white">₹{money(price.closingWalletBalance)}</b></p><p className="mt-2">Credit line after: <b className="float-right text-white">₹{money(price.availableCreditAfter)}</b></p></div><div className="rounded-2xl bg-[#2952ff] p-4"><p className="text-[9px] font-black uppercase tracking-widest text-blue-100">Total application charge</p><p className="mt-1 text-3xl font-black">₹{money(price.total)}</p></div><p className="text-[10px] text-slate-500">Balances: Wallet ₹{money(balances.walletBalance)} · Credit ₹{money(balances.creditLineBalance)}</p></div></aside></div>
  <footer className="flex flex-col justify-between gap-3 border-t bg-slate-50 p-5 sm:flex-row"><button onClick={onBack} className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Discard</button><div className="flex flex-col gap-3 sm:flex-row"><button onClick={saveDraft} disabled={busy||Boolean(uploading)} className="flex items-center justify-center gap-2 rounded-xl border bg-white px-6 py-3 text-sm font-bold disabled:opacity-50"><Save size={16}/>Save Draft</button><button onClick={submit} disabled={busy||Boolean(uploading)} className={`flex items-center justify-center gap-2 rounded-xl px-7 py-3 text-sm font-black disabled:opacity-50 ${valid?"bg-[#2952ff] text-white":"border bg-slate-100 text-slate-500"}`}>{valid?"Confirm Audit & Recover":"Complete Information"}<ArrowRight size={16}/></button></div></footer>
 </div></section>
}
function Mode({active,onClick,title,subtitle}){return <button onClick={onClick} className={`rounded-lg py-3 text-center ${active?"border border-blue-200 bg-white text-[#2952ff] shadow-sm":"text-slate-400"}`}><b className="block text-[10px] uppercase">{title}</b><span className="text-[8px] font-bold uppercase opacity-70">{subtitle}</span></button>}
function Field({label,icon,children}){return <label className="block"><span className="mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{icon}{label}<em className="not-italic text-rose-500">*</em></span><span className="iem-field-control block">{children}</span></label>}
function Ledger({label,value}){return <div className="flex items-center justify-between gap-3 text-xs"><span className="text-slate-400">{label}</span><b className="text-rose-400">− ₹{money(value)}</b></div>}
