import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { ArrowLeft, ArrowRight, Battery, Cpu, Disc, Download, FileText, Info, Layers, ListOrdered, Receipt, Save, Trash2, Upload, Wallet, Weight, X, Zap } from "lucide-react";
import { downloadEprDocument, getEprConfiguration, getEprLedger, getEprQuote, getEprRequests, removeEprDocument, saveEprDraft, submitEpr, uploadEprDocument } from "../../services/eprAuthorizationService";

const emptyFile={status:"Not Uploaded",name:null};
export default function EprAuthorizationWorkflow({onBack}){
  const navigate=useNavigate();
  const[configuration,setConfiguration]=useState(null);const[quote,setQuote]=useState(null);const[ledger,setLedger]=useState({transactions:[]});
  const[requestId,setRequestId]=useState(null);const[draftCode,setDraftCode]=useState("");const[wasteType,setWasteType]=useState("plastic");const[requestType,setRequestType]=useState("new");const[weightMT,setWeightMT]=useState("");const[documentCount,setDocumentCount]=useState("");const[files,setFiles]=useState({});
  const[initializing,setInitializing]=useState(true);const[busy,setBusy]=useState(false);const[uploading,setUploading]=useState("");const[quoteLoading,setQuoteLoading]=useState(false);const[error,setError]=useState("");const skipQuote=useRef(false);
  useEffect(()=>{let active=true;Promise.all([getEprConfiguration(),getEprRequests(),getEprLedger()]).then(async([config,requestData,ledgerData])=>{const draft=requestData.requests?.find(item=>item.status==="DRAFT");const body=draft?.payload||{};const type=body.requestType||"new";const waste=body.wasteType||"plastic";const weight=body.weightMT??"";const quoteData=await getEprQuote({requestType:type,wasteType:waste,weightMT:Number(weight||0)});if(!active)return;const restored=Object.fromEntries((config.service.documents||[]).map(item=>[item.id,{...emptyFile}]));for(const document of draft?.documents||[])restored[document.document_key||document.documentKey]={status:"Uploaded",name:document.original_name||document.name,size:Number(document.size_bytes||document.size||0)};setConfiguration(config);setLedger(ledgerData);setQuote(quoteData);skipQuote.current=true;setRequestType(type);setWasteType(waste);setWeightMT(weight);setDocumentCount(body.documentCount??"");setRequestId(draft?.id||null);setDraftCode(draft?.request_code||"");setFiles(restored);}).catch(()=>active&&setError("Unable to load EPR Authorisation." )).finally(()=>active&&setInitializing(false));return()=>{active=false};},[]);
  useEffect(()=>{if(initializing)return;if(skipQuote.current){skipQuote.current=false;return}const timer=window.setTimeout(()=>{setQuoteLoading(true);getEprQuote({requestType,wasteType,weightMT:Number(weightMT||0)}).then(data=>{setQuote(data);setError("");}).catch(()=>setError("Unable to calculate EPR pricing.")).finally(()=>setQuoteLoading(false));},200);return()=>window.clearTimeout(timer);},[requestType,wasteType,weightMT,initializing]);
  const config=configuration?.service;
  const documents=useMemo(()=>(config?.documents||[]).filter(item=>(item.availableFor||item.requiredFor||[]).includes(requestType)),[config,requestType]);
  const payload=()=>({requestId,wasteType,requestType,weightMT:Number(weightMT||0),documentCount:Number(documentCount||0),documents:files});
  const valid=Boolean(Number(weightMT)>0&&Number.isInteger(Number(documentCount))&&Number(documentCount)>0&&documents.filter(item=>item.requiredFor?.includes(requestType)).every(item=>files[item.id]?.status==="Uploaded"));
  async function ensureDraft(){if(requestId)return requestId;const data=await saveEprDraft(payload());setRequestId(data.request.id);setDraftCode(data.request.request_code);return data.request.id;}
  async function selectFile(key,event){const file=event.target.files?.[0];event.target.value="";if(!file)return;try{setUploading(key);const id=await ensureDraft();const data=await uploadEprDocument(id,key,file);setFiles(current=>({...current,[key]:{status:"Uploaded",name:data.document.name,size:data.document.size}}));}catch(e){Swal.fire("Upload failed",e.response?.data?.message||"The document could not be uploaded.","error");}finally{setUploading("");}}
  async function removeFile(key){if(!requestId)return;try{setUploading(key);await removeEprDocument(requestId,key);setFiles(current=>({...current,[key]:{...emptyFile}}));}catch(e){Swal.fire("Unable to remove document",e.response?.data?.message||"Please try again.","error");}finally{setUploading("");}}
  async function downloadFile(key){try{await downloadEprDocument(requestId,key,files[key]?.name);}catch(e){Swal.fire("Download failed",e.response?.data?.message||"The document could not be downloaded.","error");}}
  async function saveDraft(){try{setBusy(true);const data=await saveEprDraft(payload());setRequestId(data.request.id);setDraftCode(data.request.request_code);await Swal.fire({icon:"success",title:"EPR draft saved",text:`${data.request.request_code} can be resumed later.`,confirmButtonColor:"#2952ff"});}catch(e){Swal.fire("Unable to save draft",e.response?.data?.message||"Please try again.","error");}finally{setBusy(false);}}
  async function submit(){if(!valid)return;try{setBusy(true);const data=await submitEpr(payload());const[nextQuote,nextLedger]=await Promise.all([getEprQuote({requestType,wasteType,weightMT:Number(weightMT)}),getEprLedger()]);setQuote(nextQuote);setLedger(nextLedger);window.dispatchEvent(new CustomEvent("wallet:updated",{detail:{balance:data.balances.walletBalance,creditLine:data.balances.creditLineBalance}}));await Swal.fire({icon:"success",title:"EPR request submitted",text:`${data.request.request_code} has been sent to the admin team.`,confirmButtonColor:"#2952ff"});onBack();}catch(e){if(e.response?.status===402){const code=e.response?.data?.errors?.code;const message=code==="INSUFFICIENT_WALLET"?"Wallet balance is insufficient. Please top up your Wallet.":code==="INSUFFICIENT_CREDIT_LINE"?"Credit Line balance is insufficient. Please top up your Credit Line.":"Wallet and Credit Line balances are insufficient. Please top up both.";const result=await Swal.fire({icon:"warning",title:"Top up required",text:message,showCancelButton:true,confirmButtonText:"Go to Wallet & Credit",confirmButtonColor:"#2952ff"});if(result.isConfirmed)navigate("/client/wallet-credit#add-credit");}else Swal.fire("Unable to submit EPR request",e.response?.data?.message||"Please try again.","error");}finally{setBusy(false);}}
  if(initializing)return <div className="mx-auto max-w-7xl p-6"><div className="min-h-[700px] animate-pulse rounded-[30px] bg-white shadow-lg"/></div>;
  const costs=quote||{};
  return <div className="min-h-[calc(100vh-7rem)]"><div className="mx-auto max-w-7xl px-4 py-4 lg:px-6">
    {error&&<div className="mb-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}
    {draftCode&&<div className="mb-3 flex gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-3 text-blue-900"><Save size={17}/><div><b className="text-xs">Draft {draftCode} restored</b><p className="text-[11px] text-blue-600">Continue the EPR authorisation or annual return.</p></div></div>}
    <div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.08)]">
      <header className="flex justify-between border-b p-5"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#2952ff] text-white"><Trash2/></div><div><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Back to Compliance</button><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black uppercase">EPR Authorization &amp; Returns</h1><span className="rounded-full bg-slate-900 px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-white">CPCB Audit</span></div><p className="mt-1 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">{draftCode||"New EPR Request"}<Zap size={11} className="text-amber-500"/> SLA Priority</p></div></div><button onClick={onBack}><X className="text-slate-400"/></button></header>
      <div className="grid gap-5 p-5 xl:grid-cols-[minmax(0,1.45fr)_360px]"><div className="space-y-5">
        <div><p className="mb-3 text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Waste Discipline</p><div className="grid grid-cols-2 gap-2 rounded-2xl border border-slate-200 bg-slate-100 p-1.5 sm:grid-cols-4">{(config?.wasteTypes||[]).map(type=><WasteButton key={type.id} type={type} active={wasteType===type.id} onClick={()=>setWasteType(type.id)}/>)}</div></div>
        <div className="grid grid-cols-2 gap-2 rounded-2xl border border-slate-100 bg-slate-50 p-1">{(config?.requestTypes||[]).map(type=><button key={type.id} onClick={()=>setRequestType(type.id)} className={`rounded-xl px-3 py-3 ${requestType===type.id?"bg-white text-[#2952ff] shadow-sm":"text-slate-400"}`}><b className="block text-[11px] uppercase">{type.id==="new"?"Authorization":"Annual Return"}</b><span className="text-[9px] font-bold uppercase">{type.id==="new"?"Registration (₹10,000)":"Obligation (₹5,000)"}</span></button>)}</div>
        <div className="grid gap-4 md:grid-cols-2"><Field label="Total Quantity (MT / Annum)" icon={<Weight size={12}/>}><input type="number" min="0.001" step="0.001" placeholder="Weight for Slab Selection" value={weightMT} onChange={e=>setWeightMT(e.target.value)}/></Field><Field label="Total SB / BOE (Last FY)" icon={<ListOrdered size={12}/>}><input type="number" min="1" step="1" placeholder="Procurement Count" value={documentCount} onChange={e=>setDocumentCount(e.target.value)}/></Field></div>
        <div><h2 className="mb-3 flex items-center gap-2 text-[11px] font-black uppercase tracking-[.18em]"><Upload size={14}/> Required Statutory Evidence</h2><div className="space-y-2">{documents.map(document=>{const required=document.requiredFor?.includes(requestType);return <article key={document.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3"><FileText className={files[document.id]?.status==="Uploaded"?"text-emerald-500":"text-slate-400"}/><div className="min-w-0 flex-1"><b className="block text-xs uppercase">{document.label}{required&&<em className="ml-2 not-italic text-[9px] text-rose-500">REQUIRED</em>}</b><span className={`block truncate text-[10px] ${files[document.id]?.status==="Uploaded"?"text-emerald-600":"text-slate-400"}`}>{files[document.id]?.name||"Compliance file required"}</span></div>{files[document.id]?.status==="Uploaded"&&<button onClick={()=>downloadFile(document.id)} title="Download uploaded document" className="text-[#2952ff]"><Download size={16}/></button>}{files[document.id]?.status==="Uploaded"&&<button onClick={()=>removeFile(document.id)} className="text-[10px] font-black uppercase text-rose-500">Remove</button>}<label className="cursor-pointer rounded-lg border bg-slate-50 px-4 py-2 text-[10px] font-black uppercase">{uploading===document.id?"Uploading...":files[document.id]?.status==="Uploaded"?"Replace":"Upload"}<input className="sr-only" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.jpg,.jpeg,.png" onChange={e=>selectFile(document.id,e)}/></label></article>})}</div></div>
        <div className="flex gap-3 rounded-2xl border border-amber-100 bg-amber-50 p-4 text-amber-900"><Info size={16}/><p className="text-[10px] font-medium uppercase leading-relaxed"><strong>Statutory Slabs:</strong> {weightMT?`Audit for ${weightMT} MT initiated. `:""}Plastic EPR fees are weight-based. The official fee listed is for the base SME slab. High-volume imports will require supplemental payment post-scrutiny.</p></div>
      </div><aside className={`overflow-hidden rounded-3xl bg-slate-900 text-white shadow-xl xl:sticky xl:top-24 xl:self-start ${quoteLoading?"opacity-80":""}`}><div className="flex items-center gap-2 border-b border-white/10 p-5 text-blue-400"><Receipt size={16}/><span className="text-[10px] font-black uppercase tracking-[.2em]">Transaction Ledger (INR)</span></div><div className="space-y-5 p-5"><Ledger title="Prepaid Wallet" balance={costs.openingWalletBalance} lines={[["CPCB Official Fee",costs.officialFee]]} after={costs.closingWalletBalance}/><Ledger title="Corporate Credit Line" balance={costs.currentCreditLimit} lines={[["Application Drafting",costs.draftingFee],["Compliance Shield",costs.shieldPremium],["GST",costs.gst]]} after={costs.availableCreditAfter}/></div><div className="flex justify-between bg-[#2952ff] p-5"><div><span className="text-[9px] font-black uppercase text-blue-100">Total EPR Debit</span><b className="block text-2xl">₹{Number(costs.total||0).toLocaleString("en-IN")}</b></div><span className="text-right text-[9px] uppercase text-white/70">SLA: {config?.sla}<br/>{ledger.transactions.length} ledger entries</span></div></aside></div>
      <footer className="flex flex-col justify-between gap-3 border-t bg-slate-50 p-5 sm:flex-row"><button onClick={onBack} className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Discard</button><div className="flex gap-3"><button onClick={saveDraft} disabled={busy} className="flex items-center gap-2 rounded-xl border bg-white px-6 py-3 text-sm font-bold"><Save size={16}/> Save Draft</button><button onClick={submit} disabled={busy||!valid} className={`flex items-center gap-2 rounded-xl px-7 py-3 text-sm font-black ${valid?"bg-slate-900 text-white":"bg-slate-200 text-slate-400"}`}>{valid?"Confirm & File EPR":"Incomplete Audit"}<ArrowRight size={16}/></button></div></footer>
    </div></div></div>;
}
function WasteButton({type,active,onClick}){const icons={plastic:Layers,"e-waste":Cpu,battery:Battery,tyre:Disc};const Icon=icons[type.id]||Layers;return <button onClick={onClick} className={`flex flex-col items-center rounded-xl px-1 py-3 text-center transition ${active?"border border-slate-100 bg-white text-slate-900 shadow-md":"text-slate-400 opacity-70"}`}><Icon size={18} className={active?"text-[#2952ff]":""}/><b className="mt-1.5 text-[9px] uppercase">{type.label}</b></button>}
function Field({label,icon,children}){return <label className="space-y-1.5"><span className="flex items-center gap-2 px-1 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">{icon}{label}</span><span className="iem-field-control block">{children}</span></label>}
function Ledger({title,balance,lines,after}){return <div><div className="mb-3 flex justify-between text-[10px] font-black uppercase tracking-widest text-slate-500"><span>{title}</span><Wallet size={14}/></div><div className="space-y-2 text-xs"><div className="flex justify-between"><span className="text-slate-400">Opening Balance</span><b>₹{Number(balance||0).toLocaleString("en-IN")}</b></div>{lines.map(([label,amount])=><div key={label} className="flex justify-between border-t border-white/10 pt-2"><span className="text-slate-400">{label}</span><b className="text-rose-400">- ₹{Number(amount||0).toLocaleString("en-IN")}</b></div>)}<div className="flex justify-between border-t border-white/10 pt-2"><span className="text-blue-400">Available Post-Task</span><b>₹{Number(after||0).toLocaleString("en-IN")}</b></div></div></div>}
