import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { Activity, ArrowLeft, ArrowRight, Award, Building2, CheckCircle2, Download, FileText, Fingerprint, Hash, Info, LoaderCircle, Receipt, RefreshCw, Save, Trash2, Upload, Users, X, Zap } from "lucide-react";
import { downloadLicensingDocument, getLicensingConfiguration, getLicensingLedger, getLicensingQuote, getLicensingRequests, removeLicensingDocument, saveLicensingDraft, submitLicensingRequest, uploadLicensingDocument } from "../../services/licensingService";

const SLUG = "e-rcmc-issuance";
const EPCS = [["CHEMEXCIL", "CHEMEXCIL · Chemicals"], ["EEPC", "EEPC · Engineering"], ["APEDA", "APEDA · Agriculture"], ["PHARMEXCIL", "PHARMEXCIL · Pharma"], ["FIEO", "FIEO · General"], ["GJEPC", "GJEPC · Gems & Jewellery"]];
const money = (value) => new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(Number(value || 0));
const errorText = (error, fallback) => error?.response?.data?.message || error?.message || fallback;
const keyOf = (item) => item?.document_key || item?.documentKey || "";
const nameOf = (item) => item?.original_name || item?.name || "Uploaded document";

export default function ERcmcWorkflow({ onBack }) {
  const navigate = useNavigate(); const fileInputs = useRef({});
  const [configuration, setConfiguration] = useState(null); const [entity, setEntity] = useState({}); const [draft, setDraft] = useState(null);
  const [form, setForm] = useState({ requestType: "New", exporterType: "Merchant", iecNumber: "", selectedEpc: "", annualTurnover: "", hsCode: "", prevRcmcNo: "" });
  const [documents, setDocuments] = useState([]); const [quote, setQuote] = useState(null); const [ledger, setLedger] = useState(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState("");

  useEffect(() => { let active = true; Promise.all([getLicensingConfiguration(SLUG), getLicensingRequests(SLUG), getLicensingLedger(SLUG)]).then(async ([configData, requestData, ledgerData]) => {
    const restored = requestData.requests?.find((item) => item.status === "DRAFT"); const nextForm = { requestType: "New", exporterType: "Merchant", iecNumber: configData.clientContext?.iecNumber || "", selectedEpc: "", annualTurnover: "", hsCode: "", prevRcmcNo: "", ...(restored?.payload?.form || {}) };
    const nextQuote = await getLicensingQuote(SLUG, nextForm); if (!active) return; setConfiguration(configData.service); setEntity(configData.clientContext || {}); setDraft(restored || null); setForm(nextForm); setDocuments(restored?.documents || []); setQuote(nextQuote); setLedger(ledgerData);
  }).catch((error) => Swal.fire("Unable to load E-RCMC", errorText(error, "Please try again shortly."), "error")).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);

  const documentRules = useMemo(() => [{ id: "gstCert", label: "Latest GST Certificate (REG-06)" }, { id: "panCard", label: "Entity PAN Card Copy" }, ...(form.exporterType === "Manufacturer" ? [{ id: "udyamCert", label: "Udyam Registration Certificate" }] : []), { id: "caTurnoverCert", label: `${form.selectedEpc || "Council"} CA Turnover Certificate` }, { id: "membershipForm", label: "Signed Council Membership Form" }], [form.exporterType, form.selectedEpc]);
  async function updateField(field, value) { const next = { ...form, [field]: value }; setForm(next); try { setQuote(await getLicensingQuote(SLUG, next)); } catch { setQuote(null); } }
  function validationMessage() { if (!EPCS.some(([id]) => id === form.selectedEpc)) return "Select the applicable Export Promotion Council."; if (Number(form.annualTurnover) <= 0) return "Enter the previous financial year turnover."; if (form.requestType === "New" && !/^\d{4}$/.test(form.hsCode)) return "Enter a valid 4-digit main HS code."; if (form.requestType === "Renewal" && form.prevRcmcNo.trim().length < 6) return "Enter the previous RCMC number."; const uploaded = new Set(documents.map(keyOf)); const missing = documentRules.find((item) => !uploaded.has(item.id)); return missing ? `Upload the required document: ${missing.label}.` : ""; }
  async function persistDraft(showMessage = true) { const response = await saveLicensingDraft(SLUG, { requestId: draft?.id, form }); setDraft(response.request); if (showMessage) await Swal.fire({ icon: "success", title: "E-RCMC draft saved", text: `${response.request.request_code} can be resumed later.`, confirmButtonColor: "#2952ff" }); return response.request; }
  async function saveDraft() { try { setBusy(true); await persistDraft(); } catch (error) { Swal.fire("Unable to save draft", errorText(error, "Please try again."), "error"); } finally { setBusy(false); } }
  async function uploadDocument(key, event) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; try { setUploading(key); const request = draft || await persistDraft(false); const response = await uploadLicensingDocument(SLUG, request.id, key, file); setDocuments((current) => [...current.filter((item) => keyOf(item) !== key), response.document]); } catch (error) { Swal.fire("Upload failed", errorText(error, "The document could not be uploaded."), "error"); } finally { setUploading(""); } }
  async function removeDocument(key) { if (!draft) return; try { setUploading(key); await removeLicensingDocument(SLUG, draft.id, key); setDocuments((current) => current.filter((item) => keyOf(item) !== key)); } catch (error) { Swal.fire("Unable to remove file", errorText(error, "Please try again."), "error"); } finally { setUploading(""); } }
  async function downloadDocument(key, name) { try { await downloadLicensingDocument(SLUG, draft.id, key, name); } catch (error) { Swal.fire("Unable to download file", errorText(error, "Please try again."), "error"); } }
  async function submit() { const missing = validationMessage(); if (missing) return Swal.fire({ icon: "error", title: "E-RCMC application is incomplete", text: missing, confirmButtonColor: "#2952ff" }); try { setBusy(true); const request = await persistDraft(false); const response = await submitLicensingRequest(SLUG, { requestId: request.id, form }); setLedger(await getLicensingLedger(SLUG)); window.dispatchEvent(new CustomEvent("wallet:updated", { detail: { balance: response.balances?.walletBalance, creditLine: response.balances?.creditLineBalance } })); await Swal.fire({ icon: "success", title: "E-RCMC application submitted", text: `${response.request.request_code} has been sent to the admin team.`, confirmButtonColor: "#2952ff" }); onBack(); } catch (error) { if (error.response?.status === 402) { const result = await Swal.fire({ icon: "warning", title: "Top up required", text: "Your Wallet or Credit Line balance is insufficient.", showCancelButton: true, confirmButtonText: "Go to Wallet & Credit", confirmButtonColor: "#2952ff" }); if (result.isConfirmed) navigate("/client/wallet-credit#add-credit"); } else Swal.fire("Unable to submit E-RCMC", errorText(error, "Please verify the application and try again."), "error"); } finally { setBusy(false); } }

  if (loading || !configuration) return <div className="flex min-h-[520px] items-center justify-center text-slate-500"><LoaderCircle className="mr-2 animate-spin" /> Loading E-RCMC…</div>;
  const valid = !validationMessage(); const price = quote || {}; const balances = ledger?.balances || {};
  return <section className="mx-auto max-w-[1370px] animate-in fade-in duration-300"><div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.08)]">
    <header className="flex items-start justify-between border-b px-5 py-5 md:px-7"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#2952ff] text-white shadow-lg shadow-blue-100"><Award /></div><div><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} /> Back to Service Store</button><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black uppercase">E-RCMC Issuance & Audit</h1><span className="rounded-full bg-slate-900 px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-white">FTP 2023</span></div><p className="mt-1 flex flex-wrap items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-500"><Fingerprint size={11} className="text-[#2952ff]" />{draft?.request_code || "Reference generated on save"}<Zap size={11} className="text-amber-500" /> 5–7 working days</p></div></div><button onClick={onBack} aria-label="Close E-RCMC workflow"><X className="text-slate-400" /></button></header>
    <div className="flex flex-wrap items-center justify-between gap-2 border-b bg-blue-50/70 px-5 py-3 text-[10px] font-black uppercase tracking-[.14em] text-blue-700"><span className="flex items-center gap-2"><RefreshCw size={12} /> Entity: {entity.companyName || "Company"}{form.iecNumber ? ` · IEC ${form.iecNumber}` : ""}</span><span>DGFT profile sync</span></div>
    <div className="grid gap-6 p-5 xl:grid-cols-[minmax(0,1.4fr)_360px] md:p-7"><div className="space-y-6">
      <div className="grid grid-cols-2 gap-2 rounded-2xl border bg-slate-100 p-1"><Mode active={form.requestType === "New"} onClick={() => updateField("requestType", "New")} title="New Issuance" subtitle="Council registration" /><Mode active={form.requestType === "Renewal"} onClick={() => updateField("requestType", "Renewal")} title="Renewal" subtitle="Validity extension" /></div>
      <div className="grid grid-cols-2 gap-3"><Choice active={form.exporterType === "Merchant"} onClick={() => updateField("exporterType", "Merchant")} icon={<Users size={16} />} label="Merchant Exporter" /><Choice active={form.exporterType === "Manufacturer"} onClick={() => updateField("exporterType", "Manufacturer")} icon={<Building2 size={16} />} label="Manufacturer Exporter" /></div>
      <div className="grid gap-4 md:grid-cols-2"><Field label="Export Promotion Council" required><select value={form.selectedEpc} onChange={(e) => updateField("selectedEpc", e.target.value)}><option value="">Select EPC Council…</option>{EPCS.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field>{form.requestType === "New" ? <Field label="Main HS Code" icon={<Hash size={12} />} required><input inputMode="numeric" maxLength={4} value={form.hsCode} onChange={(e) => updateField("hsCode", e.target.value.replace(/\D/g, ""))} placeholder="E.g. 8413" /></Field> : <Field label="Previous RCMC Number" required><input value={form.prevRcmcNo} onChange={(e) => updateField("prevRcmcNo", e.target.value.toUpperCase())} placeholder="E.g. EEPC/WR/12345/21" /></Field>}<Field label="Previous FY Turnover (INR)" icon={<Activity size={12} />} required><input type="number" min="1" value={form.annualTurnover} onChange={(e) => updateField("annualTurnover", e.target.value)} placeholder="Used for council fee tiering" /></Field><Field label="IEC Number"><input value={form.iecNumber} readOnly placeholder="Synced from profile" /></Field></div>
      <div><h2 className="mb-3 text-[11px] font-black uppercase tracking-[.18em] text-slate-800">Required audit evidence</h2><div className="space-y-2">{documentRules.map((item) => { const saved = documents.find((doc) => keyOf(doc) === item.id); return <article key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3 hover:border-blue-300"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${saved ? "bg-emerald-50 text-emerald-600" : "bg-slate-50 text-slate-400"}`}>{saved ? <CheckCircle2 size={20} /> : <FileText size={20} />}</div><div className="min-w-0 flex-1"><b className="block text-xs">{item.label}<em className="ml-2 not-italic text-[9px] uppercase text-rose-500">Required</em></b><span className={`block truncate text-[10px] ${saved ? "text-emerald-600" : "text-slate-400"}`}>{saved ? nameOf(saved) : "PDF, DOC, XLS, JPG or PNG · maximum 20 MB"}</span></div>{saved && <><button onClick={() => downloadDocument(item.id, nameOf(saved))} className="rounded-lg p-2 text-[#2952ff]" aria-label={`Download ${item.label}`}><Download size={16} /></button><button onClick={() => removeDocument(item.id)} className="rounded-lg p-2 text-rose-500" aria-label={`Remove ${item.label}`}><Trash2 size={16} /></button></>}<button onClick={() => fileInputs.current[item.id]?.click()} disabled={Boolean(uploading)} className="rounded-lg border bg-white px-4 py-2 text-[10px] font-black uppercase disabled:opacity-50"><Upload className="mr-1 inline" size={14} />{uploading === item.id ? "Uploading" : saved ? "Replace" : "Upload"}</button><input ref={(node) => { fileInputs.current[item.id] = node; }} type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={(event) => uploadDocument(item.id, event)} /></article>; })}</div></div>
      <div className="flex gap-3 rounded-2xl border border-amber-100 bg-amber-50 p-4 text-[10px] font-semibold uppercase leading-relaxed text-amber-800"><Info className="shrink-0" size={17} /><p>{form.selectedEpc ? `The CA turnover certificate must use the ${form.selectedEpc}-approved format. Generic certificates may be rejected during council scrutiny.` : "Select an Export Promotion Council before preparing the council-specific CA certificate."}</p></div>
    </div><aside className="h-fit overflow-hidden rounded-3xl bg-slate-950 text-white shadow-xl xl:sticky xl:top-24"><div className="flex items-center gap-2 border-b border-white/10 p-5 text-blue-400"><Receipt size={16} /><span className="text-[10px] font-black uppercase tracking-[.2em]">Transaction Ledger</span></div><div className="space-y-4 p-5"><Ledger label="Council membership fee" value={price.officialFee} /><Ledger label="Technical audit & drafting" value={price.draftingFee} /><Ledger label="GST (18%)" value={price.gst} /><div className="border-t border-white/10 pt-3 text-xs text-slate-400"><p>Wallet after: <b className="float-right text-white">₹{money(price.closingWalletBalance)}</b></p><p className="mt-2">Credit line after: <b className="float-right text-white">₹{money(price.availableCreditAfter)}</b></p></div><div className="rounded-2xl bg-[#2952ff] p-4"><p className="text-[9px] font-black uppercase tracking-widest text-blue-100">Total application charge</p><p className="mt-1 text-3xl font-black">₹{money(price.total)}</p></div><p className="text-[10px] text-slate-500">Balances: Wallet ₹{money(balances.walletBalance)} · Credit ₹{money(balances.creditLineBalance)}</p></div></aside></div>
    <footer className="flex flex-col justify-between gap-3 border-t bg-slate-50 p-5 sm:flex-row"><button onClick={onBack} className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Discard</button><div className="flex flex-col gap-3 sm:flex-row"><button onClick={saveDraft} disabled={busy || Boolean(uploading)} className="flex items-center justify-center gap-2 rounded-xl border bg-white px-6 py-3 text-sm font-bold disabled:opacity-50"><Save size={16} /> Save Draft</button><button onClick={submit} disabled={busy || Boolean(uploading)} className={`flex items-center justify-center gap-2 rounded-xl px-7 py-3 text-sm font-black disabled:opacity-50 ${valid ? "bg-[#2952ff] text-white" : "border bg-slate-100 text-slate-500"}`}>{valid ? "Complete Information" : "Incomplete Audit"}<ArrowRight size={16} /></button></div></footer>
  </div></section>;
}

function Mode({ active, onClick, title, subtitle }) { return <button onClick={onClick} className={`rounded-xl px-3 py-3 text-center ${active ? "border border-blue-200 bg-white text-[#2952ff] shadow-sm" : "text-slate-400"}`}><b className="block text-[10px] font-black uppercase">{title}</b><span className="mt-1 block text-[9px] font-bold uppercase opacity-70">{subtitle}</span></button>; }
function Choice({ active, onClick, icon, label }) { return <button onClick={onClick} className={`flex items-center justify-center gap-2 rounded-xl border p-3 text-[10px] font-black uppercase ${active ? "border-blue-300 bg-blue-50 text-[#2952ff]" : "border-slate-200 text-slate-400"}`}>{icon}{label}</button>; }
function Field({ label, required = false, icon = null, children }) { return <label className="block"><span className="mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{icon}{label}{required && <em className="not-italic text-rose-500">*</em>}</span><span className="iem-field-control block">{children}</span></label>; }
function Ledger({ label, value }) { return <div className="flex items-center justify-between gap-3 text-xs"><span className="text-slate-400">{label}</span><b className="text-rose-400">− ₹{money(value)}</b></div>; }
