import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { ArrowLeft, ArrowRight, Award, Beef, CheckCircle2, Download, FileText, Fingerprint, Globe, Info, LoaderCircle, Receipt, RefreshCw, Save, ShieldAlert, Soup, Trash2, Upload, X, Zap } from "lucide-react";
import { downloadLicensingDocument, getLicensingConfiguration, getLicensingLedger, getLicensingQuote, getLicensingRequests, removeLicensingDocument, saveLicensingDraft, submitLicensingRequest, uploadLicensingDocument } from "../../services/licensingService";

const SLUG="halal-certification";
const MARKETS=[["GSO","GSO · GCC Countries"],["SMIIC","SMIIC · OIC / Turkey"],["SFDA","SFDA · Saudi Arabia"],["JAKIM","JAKIM · Malaysia"],["MUI","MUI · Indonesia"]];
const money=value=>new Intl.NumberFormat("en-IN",{maximumFractionDigits:2}).format(Number(value||0));
const errorText=(error,fallback)=>error?.response?.data?.message||error?.message||fallback;const keyOf=item=>item?.document_key||item?.documentKey||"";const nameOf=item=>item?.original_name||item?.name||"Uploaded document";

export default function HalalCertificationWorkflow({onBack}){
 const navigate=useNavigate(),fileInputs=useRef({});const[configuration,setConfiguration]=useState(null),[entity,setEntity]=useState({}),[draft,setDraft]=useState(null);const[form,setForm]=useState({requestMode:"Meat",requestType:"Registration",iecNumber:"",targetMarket:"GSO"});const[documents,setDocuments]=useState([]),[quote,setQuote]=useState(null),[ledger,setLedger]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uploading,setUploading]=useState("");
 useEffect(()=>{let active=true;Promise.all([getLicensingConfiguration(SLUG),getLicensingRequests(SLUG),getLicensingLedger(SLUG)]).then(async([configData,requestData,ledgerData])=>{const restored=requestData.requests?.find(item=>item.status==="DRAFT");const nextForm={requestMode:"Meat",requestType:"Registration",iecNumber:configData.clientContext?.iecNumber||"",targetMarket:"GSO",...(restored?.payload?.form||{})};const nextQuote=await getLicensingQuote(SLUG,nextForm);if(!active)return;setConfiguration(configData.service);setEntity(configData.clientContext||{});setDraft(restored||null);setForm(nextForm);setDocuments(restored?.documents||[]);setQuote(nextQuote);setLedger(ledgerData)}).catch(error=>Swal.fire("Unable to load Halal Certification",errorText(error,"Please try again shortly."),"error")).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const documentRules=useMemo(()=>[{id:"ingredientMatrix",label:"Detailed Ingredient Matrix with CAS Numbers"},{id:"processFlowChart",label:"Manufacturing Process & Segregation Map"},{id:"cleaningSop",label:"CIP Contamination Logs / Cleaning SOP"},...(form.requestMode==="Meat"?[{id:"qciAccreditation",label:"QCI / NABCB Accredited Body Approval"},{id:"slaughterCert",label:"Ante-Mortem & Post-Mortem Veterinary Reports"}]:[]),{id:"labAnalysisDNA",label:"DNA Test Report / Pork-Free Analysis",optional:true}],[form.requestMode]);
 async function updateField(field,value){const next={...form,[field]:value};setForm(next);try{setQuote(await getLicensingQuote(SLUG,next))}catch{setQuote(null)}}
 function validationMessage(){if(!MARKETS.some(([id])=>id===form.targetMarket))return"Select a valid target-market protocol.";const uploaded=new Set(documents.map(keyOf));const missing=documentRules.find(item=>!item.optional&&!uploaded.has(item.id));return missing?`Upload the required document: ${missing.label}.`:""}
 async function persistDraft(show=true){const response=await saveLicensingDraft(SLUG,{requestId:draft?.id,form});setDraft(response.request);if(show)await Swal.fire({icon:"success",title:"Halal audit saved",text:`${response.request.request_code} can be resumed later.`,confirmButtonColor:"#2952ff"});return response.request}
 async function saveDraft(){try{setBusy(true);await persistDraft()}catch(error){Swal.fire("Unable to save audit",errorText(error,"Please try again."),"error")}finally{setBusy(false)}}
 async function uploadDocument(key,event){const file=event.target.files?.[0];event.target.value="";if(!file)return;try{setUploading(key);const request=draft||await persistDraft(false);const response=await uploadLicensingDocument(SLUG,request.id,key,file);setDocuments(current=>[...current.filter(item=>keyOf(item)!==key),response.document])}catch(error){Swal.fire("Upload failed",errorText(error,"The document could not be uploaded."),"error")}finally{setUploading("")}}
 async function removeDocument(key){if(!draft)return;try{setUploading(key);await removeLicensingDocument(SLUG,draft.id,key);setDocuments(current=>current.filter(item=>keyOf(item)!==key))}catch(error){Swal.fire("Unable to remove file",errorText(error,"Please try again."),"error")}finally{setUploading("")}}
 async function downloadDocument(key,name){try{await downloadLicensingDocument(SLUG,draft.id,key,name)}catch(error){Swal.fire("Unable to download file",errorText(error,"Please try again."),"error")}}
 async function submit(){const missing=validationMessage();if(missing)return Swal.fire({icon:"error",title:"Halal audit is incomplete",text:missing,confirmButtonColor:"#2952ff"});try{setBusy(true);const request=await persistDraft(false);const response=await submitLicensingRequest(SLUG,{requestId:request.id,form});setLedger(await getLicensingLedger(SLUG));window.dispatchEvent(new CustomEvent("wallet:updated",{detail:{balance:response.balances?.walletBalance,creditLine:response.balances?.creditLineBalance}}));await Swal.fire({icon:"success",title:"Halal audit submitted",text:`${response.request.request_code} has been sent to the admin team.`,confirmButtonColor:"#2952ff"});onBack()}catch(error){if(error.response?.status===402){const result=await Swal.fire({icon:"warning",title:"Top up required",text:"Your Wallet or Credit Line balance is insufficient.",showCancelButton:true,confirmButtonText:"Go to Wallet & Credit",confirmButtonColor:"#2952ff"});if(result.isConfirmed)navigate("/client/wallet-credit#add-credit")}else Swal.fire("Unable to submit Halal audit",errorText(error,"Please verify the evidence and try again."),"error")}finally{setBusy(false)}}
 if(loading||!configuration)return <div className="flex min-h-[520px] items-center justify-center text-slate-500"><LoaderCircle className="mr-2 animate-spin"/>Loading Halal Certification…</div>;const valid=!validationMessage(),price=quote||{},balances=ledger?.balances||{};
 return <section className="mx-auto max-w-[1370px] animate-in fade-in duration-300"><div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.08)]">
  <header className="flex items-start justify-between border-b px-5 py-5 md:px-7"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#2952ff] text-white shadow-lg shadow-blue-100"><Award/></div><div><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/>Back to Service Store</button><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black uppercase">Halal Statutory Audit</h1><span className="rounded-full bg-slate-900 px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-white">i-CAS Compliant</span></div><p className="mt-1 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-500"><Fingerprint size={11} className="text-[#2952ff]"/>{draft?.request_code||"Reference generated on save"}<Zap size={11} className="text-amber-500"/>QCI priority</p></div></div><button onClick={onBack} aria-label="Close workflow"><X className="text-slate-400"/></button></header>
  <div className="flex flex-wrap items-center justify-between gap-2 border-b bg-blue-50/70 px-5 py-3 text-[10px] font-black uppercase tracking-[.14em] text-blue-700"><span className="flex items-center gap-2"><RefreshCw size={12}/>Entity: {entity.companyName||"Company"}{form.iecNumber?` · IEC ${form.iecNumber}`:""}</span><span>NABCB accreditation sync</span></div>
  <div className="grid gap-6 p-5 xl:grid-cols-[minmax(0,1.4fr)_360px] md:p-7"><div className="space-y-6">
   <div className="grid grid-cols-2 gap-2 rounded-2xl border bg-slate-100 p-1"><Choice active={form.requestMode==="Meat"} onClick={()=>updateField("requestMode","Meat")} icon={<Beef size={15}/>} label="Meat Products"/><Choice active={form.requestMode==="NonMeat"} onClick={()=>updateField("requestMode","NonMeat")} icon={<Soup size={15}/>} label="Food & General"/></div>
   <div className="grid grid-cols-2 gap-2 rounded-2xl border bg-slate-50 p-1"><Mode active={form.requestType==="Registration"} onClick={()=>updateField("requestType","Registration")} title="Plant Certification" subtitle="Annual registration · ₹25,000"/><Mode active={form.requestType==="Shipment"} onClick={()=>updateField("requestType","Shipment")} title="Shipment Release" subtitle="Batch-wise · ₹2,500"/></div>
   <Field label="Target Market Protocol" icon={<Globe size={12}/>} required><select value={form.targetMarket} onChange={e=>updateField("targetMarket",e.target.value)}>{MARKETS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field>
   <div className="flex gap-4 rounded-2xl border bg-slate-50 p-4"><div className="rounded-xl bg-white p-3 text-[#2952ff] shadow-sm"><Info size={21}/></div><div><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">Purity audit logic</p><p className="mt-1 text-sm font-semibold text-slate-700">{form.requestMode==="Meat"?"i-CAS reconciliation will cover slaughter controls, segregation, veterinary reporting and QCI-accredited oversight.":`Every ingredient, additive, solvent and enzyme will be screened against ${form.targetMarket} requirements.`}</p></div></div>
   <div><h2 className="mb-3 text-[11px] font-black uppercase tracking-[.18em] text-slate-800">Required statutory evidence</h2><div className="space-y-2">{documentRules.map(item=>{const saved=documents.find(doc=>keyOf(doc)===item.id);return <article key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3 hover:border-blue-300"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${saved?"bg-emerald-50 text-emerald-600":"bg-slate-50 text-slate-400"}`}>{saved?<CheckCircle2 size={20}/>:<FileText size={20}/>}</div><div className="min-w-0 flex-1"><b className="block text-xs">{item.label}<em className={`ml-2 not-italic text-[9px] uppercase ${item.optional?"text-slate-400":"text-rose-500"}`}>{item.optional?"Optional":"Required"}</em></b><span className={`block truncate text-[10px] ${saved?"text-emerald-600":"text-slate-400"}`}>{saved?nameOf(saved):"PDF, DOC, XLS, JPG or PNG · maximum 20 MB"}</span></div>{saved&&<><button onClick={()=>downloadDocument(item.id,nameOf(saved))} className="rounded-lg p-2 text-[#2952ff]" aria-label={`Download ${item.label}`}><Download size={16}/></button><button onClick={()=>removeDocument(item.id)} className="rounded-lg p-2 text-rose-500" aria-label={`Remove ${item.label}`}><Trash2 size={16}/></button></>}<button onClick={()=>fileInputs.current[item.id]?.click()} disabled={Boolean(uploading)} className="rounded-lg border bg-white px-4 py-2 text-[10px] font-black uppercase disabled:opacity-50"><Upload className="mr-1 inline" size={14}/>{uploading===item.id?"Uploading":saved?"Replace":"Upload"}</button><input ref={node=>{fileInputs.current[item.id]=node}} type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={event=>uploadDocument(item.id,event)}/></article>})}</div></div>
   {form.requestMode==="Meat"&&<div className="flex gap-3 rounded-2xl border border-rose-100 bg-rose-50 p-4 text-[10px] font-black uppercase leading-relaxed text-rose-800"><ShieldAlert className="shrink-0" size={18}/><p>Halal meat certification must be issued through an appropriately accredited body. Accreditation and veterinary evidence are mandatory for this route.</p></div>}
  </div><aside className="h-fit overflow-hidden rounded-3xl bg-slate-950 text-white shadow-xl xl:sticky xl:top-24"><div className="flex items-center gap-2 border-b border-white/10 p-5 text-blue-400"><Receipt size={16}/><span className="text-[10px] font-black uppercase tracking-[.2em]">Settlement Ledger</span></div><div className="space-y-4 p-5"><Ledger label="Official accreditation fee" value={price.officialFee}/><Ledger label="Technical dossier & audit" value={price.draftingFee}/><Ledger label="Purity assurance premium" value={price.purityPremium}/><Ledger label="GST (18%)" value={price.gst}/><div className="border-t border-white/10 pt-3 text-xs text-slate-400"><p>Wallet after: <b className="float-right text-white">₹{money(price.closingWalletBalance)}</b></p><p className="mt-2">Credit line after: <b className="float-right text-white">₹{money(price.availableCreditAfter)}</b></p></div><div className="rounded-2xl bg-[#2952ff] p-4"><p className="text-[9px] font-black uppercase tracking-widest text-blue-100">Total audit debit</p><p className="mt-1 text-3xl font-black">₹{money(price.total)}</p></div><p className="text-[10px] text-slate-500">Balances: Wallet ₹{money(balances.walletBalance)} · Credit ₹{money(balances.creditLineBalance)}</p></div></aside></div>
  <footer className="flex flex-col justify-between gap-3 border-t bg-slate-50 p-5 sm:flex-row"><button onClick={onBack} className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Discard</button><div className="flex flex-col gap-3 sm:flex-row"><button onClick={saveDraft} disabled={busy||Boolean(uploading)} className="flex items-center justify-center gap-2 rounded-xl border bg-white px-6 py-3 text-sm font-bold disabled:opacity-50"><Save size={16}/>Save Audit</button><button onClick={submit} disabled={busy||Boolean(uploading)} className={`flex items-center justify-center gap-2 rounded-xl px-7 py-3 text-sm font-black disabled:opacity-50 ${valid?"bg-[#2952ff] text-white":"border bg-slate-100 text-slate-500"}`}>{valid?"Confirm & File Audit":"Incomplete Audit"}<ArrowRight size={16}/></button></div></footer>
 </div></section>
}
function Choice({active,onClick,icon,label}){return <button onClick={onClick} className={`flex items-center justify-center gap-2 rounded-xl p-3 text-[10px] font-black uppercase ${active?"border border-blue-200 bg-white text-[#2952ff] shadow-sm":"text-slate-400"}`}>{icon}{label}</button>}
function Mode({active,onClick,title,subtitle}){return <button onClick={onClick} className={`rounded-xl p-3 text-center ${active?"border border-blue-200 bg-white text-[#2952ff] shadow-sm":"text-slate-400"}`}><b className="block text-[9px] uppercase">{title}</b><span className="text-[8px] font-bold uppercase opacity-70">{subtitle}</span></button>}
function Field({label,required=false,icon=null,children}){return <label className="block"><span className="mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{icon}{label}{required&&<em className="not-italic text-rose-500">*</em>}</span><span className="iem-field-control block">{children}</span></label>}
function Ledger({label,value}){return <div className="flex items-center justify-between gap-3 text-xs"><span className="text-slate-400">{label}</span><b className="text-rose-400">− ₹{money(value)}</b></div>}
