import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { Anchor, ArrowLeft, ArrowRight, Building2, CheckCircle2, Download, FileText, Fingerprint, Info, LoaderCircle, Receipt, RefreshCw, Save, Trash2, Undo2, Upload, UserCircle, X, Zap } from "lucide-react";
import { downloadLicensingDocument, getLicensingConfiguration, getLicensingLedger, getLicensingQuote, getLicensingRequests, removeLicensingDocument, saveLicensingDraft, submitLicensingRequest, uploadLicensingDocument } from "../../services/licensingService";

const SLUG = "icegate-registration";
const MODES = [["AD_CODE", "AD / IFSC", "Banking sync"], ["DSC", "DSC Update", "Signing key"], ["CONTACT", "Contact Info", "Email / mobile"]];
const AD_OPTIONS = [["BOTH", "AD Code & IFSC"], ["AD_ONLY", "Only AD Code"], ["IFSC_ONLY", "Only IFSC"]];
const money = (value) => new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(Number(value || 0));
const errorText = (error, fallback) => error?.response?.data?.message || error?.message || fallback;
const keyOf = (item) => item?.document_key || item?.documentKey || "";
const nameOf = (item) => item?.original_name || item?.name || "Uploaded document";

export default function IcegateManagementWorkflow({ onBack }) {
  const navigate = useNavigate(); const fileInputs = useRef({});
  const [configuration, setConfiguration] = useState(null); const [entity, setEntity] = useState({}); const [draft, setDraft] = useState(null);
  const [form, setForm] = useState({ modType: "AD_CODE", adOption: "BOTH", iecNumber: "", panNumber: "", portCode: "", signatoryName: "" });
  const [documents, setDocuments] = useState([]); const [quote, setQuote] = useState(null); const [ledger, setLedger] = useState(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState("");

  useEffect(() => { let active = true; Promise.all([getLicensingConfiguration(SLUG), getLicensingRequests(SLUG), getLicensingLedger(SLUG)]).then(async ([configData, requestData, ledgerData]) => {
    const restored = requestData.requests?.find((item) => item.status === "DRAFT"); const nextForm = { modType: "AD_CODE", adOption: "BOTH", iecNumber: configData.clientContext?.iecNumber || "", panNumber: "", portCode: "", signatoryName: "", ...(restored?.payload?.form || {}) };
    const nextQuote = await getLicensingQuote(SLUG, nextForm); if (!active) return; setConfiguration(configData.service); setEntity(configData.clientContext || {}); setDraft(restored || null); setForm(nextForm); setDocuments(restored?.documents || []); setQuote(nextQuote); setLedger(ledgerData);
  }).catch((error) => Swal.fire("Unable to load ICEGATE Management", errorText(error, "Please try again shortly."), "error")).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);

  const documentRules = useMemo(() => { const rules = [{ id: "companyPan", label: "Entity PAN Card Copy" }, { id: "boardResolution", label: "Authorised Signatory Board Resolution" }]; if (form.modType === "AD_CODE") { rules.unshift({ id: "bankAuthLetter", label: "Bank Authorization Letter" }); if (["BOTH", "AD_ONLY"].includes(form.adOption)) rules.push({ id: "adCodeProof", label: "AD Code Confirmation Document" }); if (["BOTH", "IFSC_ONLY"].includes(form.adOption)) rules.push({ id: "ifscProof", label: "IFSC / Bank Statement Proof" }); } if (form.modType === "DSC") rules.push({ id: "dscCertificate", label: "New DSC Public Key / Certificate" }); return rules; }, [form.modType, form.adOption]);
  async function updateField(field, value) { const next = { ...form, [field]: value }; setForm(next); try { setQuote(await getLicensingQuote(SLUG, next)); } catch { setQuote(null); } }
  function validationMessage() { if (!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(form.panNumber)) return "Enter a valid PAN in the format ABCDE1234F."; if (form.modType === "AD_CODE") { if (!/^[A-Z0-9]{5,6}$/.test(form.portCode)) return "Enter a valid 5 or 6 character customs port code."; if (!AD_OPTIONS.some(([id]) => id === form.adOption)) return "Select a valid banking update."; } else if (form.signatoryName.trim().length < 4) return "Enter the authorised signatory name exactly as shown on legal ID."; const uploaded = new Set(documents.map(keyOf)); const missing = documentRules.find((item) => !uploaded.has(item.id)); return missing ? `Upload the required document: ${missing.label}.` : ""; }
  async function persistDraft(showMessage = true) { const response = await saveLicensingDraft(SLUG, { requestId: draft?.id, form }); setDraft(response.request); if (showMessage) await Swal.fire({ icon: "success", title: "ICEGATE audit saved", text: `${response.request.request_code} can be resumed later.`, confirmButtonColor: "#2952ff" }); return response.request; }
  async function saveDraft() { try { setBusy(true); await persistDraft(); } catch (error) { Swal.fire("Unable to save audit", errorText(error, "Please try again."), "error"); } finally { setBusy(false); } }
  async function uploadDocument(key, event) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; try { setUploading(key); const request = draft || await persistDraft(false); const response = await uploadLicensingDocument(SLUG, request.id, key, file); setDocuments((current) => [...current.filter((item) => keyOf(item) !== key), response.document]); } catch (error) { Swal.fire("Upload failed", errorText(error, "The document could not be uploaded."), "error"); } finally { setUploading(""); } }
  async function removeDocument(key) { if (!draft) return; try { setUploading(key); await removeLicensingDocument(SLUG, draft.id, key); setDocuments((current) => current.filter((item) => keyOf(item) !== key)); } catch (error) { Swal.fire("Unable to remove file", errorText(error, "Please try again."), "error"); } finally { setUploading(""); } }
  async function downloadDocument(key, name) { try { await downloadLicensingDocument(SLUG, draft.id, key, name); } catch (error) { Swal.fire("Unable to download file", errorText(error, "Please try again."), "error"); } }
  async function submit() { const missing = validationMessage(); if (missing) return Swal.fire({ icon: "error", title: "ICEGATE modification is incomplete", text: missing, confirmButtonColor: "#2952ff" }); try { setBusy(true); const request = await persistDraft(false); const response = await submitLicensingRequest(SLUG, { requestId: request.id, form }); setLedger(await getLicensingLedger(SLUG)); window.dispatchEvent(new CustomEvent("wallet:updated", { detail: { balance: response.balances?.walletBalance, creditLine: response.balances?.creditLineBalance } })); await Swal.fire({ icon: "success", title: "ICEGATE modification submitted", text: `${response.request.request_code} has been sent to the admin team.`, confirmButtonColor: "#2952ff" }); onBack(); } catch (error) { if (error.response?.status === 402) { const result = await Swal.fire({ icon: "warning", title: "Top up required", text: "Your Wallet or Credit Line balance is insufficient.", showCancelButton: true, confirmButtonText: "Go to Wallet & Credit", confirmButtonColor: "#2952ff" }); if (result.isConfirmed) navigate("/client/wallet-credit#add-credit"); } else Swal.fire("Unable to submit ICEGATE modification", errorText(error, "Please verify the information and try again."), "error"); } finally { setBusy(false); } }

  if (loading || !configuration) return <div className="flex min-h-[520px] items-center justify-center text-slate-500"><LoaderCircle className="mr-2 animate-spin" /> Loading ICEGATE Management…</div>;
  const valid = !validationMessage(); const price = quote || {}; const balances = ledger?.balances || {};
  return <section className="mx-auto max-w-[1370px] animate-in fade-in duration-300"><div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.08)]">
    <header className="flex items-start justify-between border-b px-5 py-5 md:px-7"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#2952ff] text-white shadow-lg shadow-blue-100"><Undo2 /></div><div><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} /> Back to Service Store</button><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black uppercase">ICEGATE Profile Modification</h1><span className="rounded-full bg-slate-900 px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-white">Customs Compliance</span></div><p className="mt-1 flex flex-wrap items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-500"><Fingerprint size={11} className="text-[#2952ff]" />{draft?.request_code || "Reference generated on save"}<Zap size={11} className="text-amber-500" /> Priority audit</p></div></div><button onClick={onBack} aria-label="Close ICEGATE workflow"><X className="text-slate-400" /></button></header>
    <div className="flex flex-wrap items-center justify-between gap-2 border-b bg-blue-50/70 px-5 py-3 text-[10px] font-black uppercase tracking-[.14em] text-blue-700"><span className="flex items-center gap-2"><RefreshCw size={12} /> Entity: {entity.companyName || "Company"}{form.iecNumber ? ` · IEC ${form.iecNumber}` : ""}</span><span>Historical audit sync</span></div>
    <div className="grid gap-6 p-5 xl:grid-cols-[minmax(0,1.4fr)_360px] md:p-7"><div className="space-y-6">
      <div className="grid grid-cols-3 gap-2 rounded-2xl border bg-slate-100 p-1">{MODES.map(([id, title, subtitle]) => <Mode key={id} active={form.modType === id} onClick={() => updateField("modType", id)} title={title} subtitle={subtitle} />)}</div>
      {form.modType === "AD_CODE" && <div><p className="mb-3 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">Specific banking update</p><div className="grid grid-cols-3 gap-2">{AD_OPTIONS.map(([id, label]) => <button key={id} onClick={() => updateField("adOption", id)} className={`rounded-xl border px-2 py-3 text-[9px] font-black uppercase ${form.adOption === id ? "border-blue-300 bg-blue-50 text-[#2952ff]" : "border-slate-200 text-slate-400"}`}>{label}</button>)}</div></div>}
      <div className="grid gap-4 md:grid-cols-2">{form.modType === "AD_CODE" ? <Field label="Customs Port Code" icon={<Anchor size={12} />} required><input maxLength={6} value={form.portCode} onChange={(e) => updateField("portCode", e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""))} placeholder="E.g. INNSA1" /></Field> : <Field label="Name of Signatory" icon={<UserCircle size={12} />} required><input value={form.signatoryName} onChange={(e) => updateField("signatoryName", e.target.value)} placeholder="As per PAN / Aadhaar" /></Field>}<Field label="Entity PAN Number" icon={<Building2 size={12} />} required><input maxLength={10} value={form.panNumber} onChange={(e) => updateField("panNumber", e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""))} placeholder="ABCDE1234F" /></Field></div>
      <div><h2 className="mb-3 text-[11px] font-black uppercase tracking-[.18em] text-slate-800">Required audit evidence</h2><div className="space-y-2">{documentRules.map((item) => { const saved = documents.find((doc) => keyOf(doc) === item.id); return <article key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3 hover:border-blue-300"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${saved ? "bg-emerald-50 text-emerald-600" : "bg-slate-50 text-slate-400"}`}>{saved ? <CheckCircle2 size={20} /> : <FileText size={20} />}</div><div className="min-w-0 flex-1"><b className="block text-xs">{item.label}<em className="ml-2 not-italic text-[9px] uppercase text-rose-500">Required</em></b><span className={`block truncate text-[10px] ${saved ? "text-emerald-600" : "text-slate-400"}`}>{saved ? nameOf(saved) : "PDF, DOC, XLS, JPG or PNG · maximum 20 MB"}</span></div>{saved && <><button onClick={() => downloadDocument(item.id, nameOf(saved))} className="rounded-lg p-2 text-[#2952ff]" aria-label={`Download ${item.label}`}><Download size={16} /></button><button onClick={() => removeDocument(item.id)} className="rounded-lg p-2 text-rose-500" aria-label={`Remove ${item.label}`}><Trash2 size={16} /></button></>}<button onClick={() => fileInputs.current[item.id]?.click()} disabled={Boolean(uploading)} className="rounded-lg border bg-white px-4 py-2 text-[10px] font-black uppercase disabled:opacity-50"><Upload className="mr-1 inline" size={14} />{uploading === item.id ? "Uploading" : saved ? "Replace" : "Upload"}</button><input ref={(node) => { fileInputs.current[item.id] = node; }} type="file" className="hidden" accept=".pdf,.cer,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={(event) => uploadDocument(item.id, event)} /></article>; })}</div></div>
      <div className="flex gap-3 rounded-2xl border border-amber-100 bg-amber-50 p-4 text-[10px] font-semibold uppercase leading-relaxed text-amber-800"><Info className="shrink-0" size={17} /><p>{form.modType === "AD_CODE" ? "AD Code and IFSC updates require manual verification at the relevant Customs House and may take 2–3 working days to reflect." : "The authorised signatory name must exactly match the submitted legal identity records."}</p></div>
    </div><aside className="h-fit overflow-hidden rounded-3xl bg-slate-950 text-white shadow-xl xl:sticky xl:top-24"><div className="flex items-center gap-2 border-b border-white/10 p-5 text-blue-400"><Receipt size={16} /><span className="text-[10px] font-black uppercase tracking-[.2em]">Transaction Ledger</span></div><div className="space-y-4 p-5"><Ledger label="ICEGATE portal fee" value={price.officialFee} /><Ledger label="Technical audit & drafting" value={price.draftingFee} /><Ledger label="GST (18%)" value={price.gst} /><div className="border-t border-white/10 pt-3 text-xs text-slate-400"><p>Wallet after: <b className="float-right text-white">₹{money(price.closingWalletBalance)}</b></p><p className="mt-2">Credit line after: <b className="float-right text-white">₹{money(price.availableCreditAfter)}</b></p></div><div className="rounded-2xl bg-[#2952ff] p-4"><p className="text-[9px] font-black uppercase tracking-widest text-blue-100">Total application charge</p><p className="mt-1 text-3xl font-black">₹{money(price.total)}</p></div><p className="text-[10px] text-slate-500">Balances: Wallet ₹{money(balances.walletBalance)} · Credit ₹{money(balances.creditLineBalance)}</p></div></aside></div>
    <footer className="flex flex-col justify-between gap-3 border-t bg-slate-50 p-5 sm:flex-row"><button onClick={onBack} className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Discard</button><div className="flex flex-col gap-3 sm:flex-row"><button onClick={saveDraft} disabled={busy || Boolean(uploading)} className="flex items-center justify-center gap-2 rounded-xl border bg-white px-6 py-3 text-sm font-bold disabled:opacity-50"><Save size={16} /> Save Draft</button><button onClick={submit} disabled={busy || Boolean(uploading)} className={`flex items-center justify-center gap-2 rounded-xl px-7 py-3 text-sm font-black disabled:opacity-50 ${valid ? "bg-[#2952ff] text-white" : "border bg-slate-100 text-slate-500"}`}>{valid ? "Complete Information" : "Incomplete Audit"}<ArrowRight size={16} /></button></div></footer>
  </div></section>;
}

function Mode({ active, onClick, title, subtitle }) { return <button onClick={onClick} className={`rounded-xl px-2 py-3 text-center ${active ? "border border-blue-200 bg-white text-[#2952ff] shadow-sm" : "text-slate-400"}`}><b className="block text-[9px] font-black uppercase">{title}</b><span className="mt-1 block text-[8px] font-bold uppercase opacity-70">{subtitle}</span></button>; }
function Field({ label, required = false, icon = null, children }) { return <label className="block"><span className="mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{icon}{label}{required && <em className="not-italic text-rose-500">*</em>}</span><span className="iem-field-control block">{children}</span></label>; }
function Ledger({ label, value }) { return <div className="flex items-center justify-between gap-3 text-xs"><span className="text-slate-400">{label}</span><b className="text-rose-400">− ₹{money(value)}</b></div>; }
