import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Building2, Check, Download, Eye, FileText, Landmark, LoaderCircle, Pencil, Plus, Save, Send, Trash2, Upload, Users, X } from "lucide-react";
import Swal from "sweetalert2";
import { addIecItem, createIecApplication, deleteIecDocument, deleteIecItem, downloadIecDocument, getIecApplication, listIecApplications, submitIecApplication, updateIecApplication, updateIecItem, uploadIecDocument } from "../../services/iecProfileService";
import { useAuth } from "../../context/useAuth";

const steps=["Firm Details","Registered Office","Branch Details","Persons / Directors","Bank Information","Other Details","Declaration","Review & Submit"];
const emptyFirm={firmName:"",nature:"",exporterCategory:"",natureOther:"",categoryOther:"",pan:"",panName:"",birthDate:"",cin:"",hasGstin:"NO",gstin:"",sez:"NO",contact:"",email:"",eou:"NA",ehtp:"NA",stp:"NA",btp:"NA"};
const emptyAddress={address1:"",address2:"",city:"",district:"",state:"",pincode:"",dgftOffice:""};
const emptyBank={accountNumber:"",accountHolder:"",ifsc:"",bankName:"",branchAddress:"",primary:"YES",validationStatus:"NOT_VALIDATED"};
const emptyTrade={importGoods:"",importServices:"",exportGoods:"",exportServices:"",others:""};
const emptyDeclarations={declaration1:false,declaration2:false,declaration3:false,declaration4:false,declaration5:false,declaration6:false,terms:false,place:""};
const emptyBranch={branchCode:"",sez:"NO",eou:"NO",active:"YES",hasGstin:"NO",gstin:"",address1:"",address2:"",city:"",district:"",state:"",pincode:""};
const emptyPerson={din:"",foreignDirector:"NO",passport:"",panName:"",pan:"",birthDate:"",title:"Mr",name:"",fatherName:"",address1:"",address2:"",city:"",pincode:"",state:"",district:"",mobile:""};
const pan=/^[A-Z]{5}[0-9]{4}[A-Z]$/,gstin=/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/,ifsc=/^[A-Z]{4}0[A-Z0-9]{6}$/;
const statusClass={DRAFT:"bg-slate-100 text-slate-700",SUBMITTED:"bg-blue-100 text-blue-700",UNDER_REVIEW:"bg-indigo-100 text-indigo-700",ACTION_REQUIRED:"bg-amber-100 text-amber-700",APPROVED:"bg-emerald-100 text-emerald-700",REJECTED:"bg-rose-100 text-rose-700"};
const label=(value="")=>value.replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());
const toast=(icon,title,text)=>Swal.fire({icon,title,text,confirmButtonColor:"#174f92"});

export default function IecProfile(){
  const {user}=useAuth();
  const [applications,setApplications]=useState([]),[application,setApplication]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[step,setStep]=useState(1);
  const [firm,setFirm]=useState(emptyFirm),[address,setAddress]=useState(emptyAddress),[bank,setBank]=useState(emptyBank),[trade,setTrade]=useState(emptyTrade),[declarations,setDeclarations]=useState(emptyDeclarations);
  const [branch,setBranch]=useState(emptyBranch),[person,setPerson]=useState(emptyPerson),[editing,setEditing]=useState({type:"",id:null});
  const loadList=useCallback(async()=>{setLoading(true);try{setApplications((await listIecApplications()).applications||[]);}catch(e){toast("error","Unable to load IEC applications",e.response?.data?.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{loadList();},[loadList]);
  const hydrate=(app)=>{setApplication(app);setStep(app.current_step||1);setFirm({...emptyFirm,...app.firm_details});setAddress({...emptyAddress,...app.registered_address});setBank({...emptyBank,...app.bank_details});setTrade({...emptyTrade,...app.trade_details});setDeclarations({...emptyDeclarations,...app.declarations});};
  const open=async(id)=>{setLoading(true);try{hydrate((await getIecApplication(id)).application);}catch(e){toast("error","Unable to open application",e.response?.data?.message);}finally{setLoading(false);}};
  const create=async()=>{setSaving(true);try{hydrate((await createIecApplication()).application);}catch(e){toast("error","Unable to create application",e.response?.data?.message);}finally{setSaving(false);}};
  const payload=()=>({firm_details:firm,registered_address:address,bank_details:bank,trade_details:trade,declarations,current_step:step});
  const save=async(nextStep=step,quiet=false)=>{if(!application)return;setSaving(true);try{const result=await updateIecApplication(application.id,{...payload(),current_step:nextStep});hydrate(result.application);setStep(nextStep);if(!quiet)toast("success","Draft saved","Your IEC application can be continued later.");return true;}catch(e){toast("error","Save failed",e.response?.data?.message);return false;}finally{setSaving(false);}};
  const next=async()=>{if(user?.role!=="ADMIN"){setStep(Math.min(8,step+1));return;}if(!validateStep(step))return;await save(Math.min(8,step+1),true);};
  const validateStep=(current)=>{let message="";if(current===1){if(!firm.firmName||!firm.nature||!firm.exporterCategory||!firm.pan||!firm.panName||!firm.birthDate||!firm.contact||!firm.email)message="Complete all required firm fields.";else if(!pan.test(firm.pan))message="Enter a valid PAN (example: ABCDE1234F).";else if(firm.hasGstin==="YES"&&!gstin.test(firm.gstin))message="Enter a valid GSTIN.";else if(!/^\d{10}$/.test(firm.contact))message="Enter a valid 10-digit mobile number.";}if(current===2&&(!address.address1||!address.city||!address.state||!/^\d{6}$/.test(address.pincode)))message="Complete the registered address and enter a valid six-digit pincode.";if(current===5&&(!bank.accountNumber||!bank.accountHolder||!ifsc.test(bank.ifsc)))message="Complete bank details and enter a valid IFSC.";if(current===7&&([1,2,3,4,5,6].some(n=>!declarations[`declaration${n}`])||!declarations.terms||!declarations.place))message="Accept every declaration, Terms & Conditions, and enter the place.";if(message){toast("warning","Section incomplete",message);return false;}return true;};
  const saveRepeat=async(type)=>{const data=type==="branches"?branch:person;const key=type==="branches"?"branch_code":"name",value=type==="branches"?data.branchCode:data.name;if(!value)return toast("warning","Required field",`${label(key)} is required.`);if(data.pan&&!pan.test(data.pan))return toast("warning","Invalid PAN","Enter a valid PAN.");try{if(editing.type===type&&editing.id)await updateIecItem(application.id,type,editing.id,{[key]:value,details:data});else await addIecItem(application.id,type,{[key]:value,details:data});setBranch(emptyBranch);setPerson(emptyPerson);setEditing({type:"",id:null});await open(application.id);}catch(e){toast("error","Unable to save",e.response?.data?.message);}};
  const removeRepeat=async(type,id)=>{const result=await Swal.fire({icon:"warning",title:"Remove this record?",showCancelButton:true,confirmButtonText:"Remove",confirmButtonColor:"#be123c"});if(result.isConfirmed){await deleteIecItem(application.id,type,id);await open(application.id);}};
  const uploadDoc=async(event,section)=>{const file=event.target.files?.[0];if(!file)return;const form=new FormData();form.append("file",file);form.append("section",section);form.append("documentKey",section);try{await uploadIecDocument(application.id,form);await open(application.id);}catch(e){toast("error","Upload failed",e.response?.data?.message||"Use PDF, JPG or PNG up to 15 MB.");}};
  const submit=async()=>{if(!validateStep(7))return;await save(8,true);const result=await Swal.fire({icon:"question",title:"Submit IEC application?",text:"Submitted applications become read-only.",showCancelButton:true,confirmButtonText:"Submit",confirmButtonColor:"#174f92"});if(result.isConfirmed)try{hydrate((await submitIecApplication(application.id)).application);toast("success","Application submitted",application.request_code);}catch(e){toast("error","Submission blocked",e.response?.data?.message);}};
  if(loading)return <div className="flex min-h-[420px] items-center justify-center gap-2 text-slate-500"><LoaderCircle className="animate-spin"/>Loading IEC workspace…</div>;
  if(!application)return <IecDashboard applications={applications} onCreate={create} onOpen={open} saving={saving||user?.role!=="ADMIN"}/>;
  const readonly=user?.role!=="ADMIN"||!['DRAFT','ACTION_REQUIRED'].includes(application.status);
  return <div className="iec-page dashboard-page"><Hero application={application} onBack={()=>{setApplication(null);loadList();}}/><Stepper step={step} setStep={setStep}/><section className="iec-form-card">{step===1&&<FirmSection value={firm} set={setFirm} readonly={readonly} onUpload={(e)=>uploadDoc(e,"firm")}/>} {step===2&&<AddressSection value={address} set={setAddress} readonly={readonly} onUpload={(e)=>uploadDoc(e,"registered-address")}/>} {step===3&&<RepeatSection type="branches" title="Branch Details" items={application.branches} value={branch} set={setBranch} empty={emptyBranch} editing={editing} setEditing={setEditing} onSave={saveRepeat} onDelete={removeRepeat} readonly={readonly}/>} {step===4&&<RepeatSection type="persons" title="Proprietor / Partner / Director / Karta / Managing Trustee" items={application.persons} value={person} set={setPerson} empty={emptyPerson} editing={editing} setEditing={setEditing} onSave={saveRepeat} onDelete={removeRepeat} readonly={readonly}/>} {step===5&&<BankSection value={bank} set={setBank} readonly={readonly}/>} {step===6&&<TradeSection value={trade} set={setTrade} readonly={readonly}/>} {step===7&&<DeclarationSection value={declarations} set={setDeclarations} readonly={readonly}/>} {step===8&&<Review application={application} data={{firm,address,bank,trade,declarations}} setStep={setStep} onDownload={(d)=>downloadIecDocument(application.id,d)} onDelete={async(d)=>{await deleteIecDocument(application.id,d.id);await open(application.id);}} readonly={readonly}/>}<footer className="iec-footer"><button onClick={()=>setStep(Math.max(1,step-1))} disabled={step===1}><ArrowLeft size={16}/>Back</button><div>{!readonly&&<button onClick={()=>save(step)} disabled={saving}><Save size={16}/>Save Draft</button>}{step<8?<button className="primary" onClick={next}>Next<ArrowRight size={16}/></button>:!readonly&&<button className="primary" onClick={submit}><Send size={16}/>Submit Application</button>}</div></footer></section></div>;
}

function IecDashboard({applications,onCreate,onOpen,saving}){return <div className="dashboard-page"><section className="workspace-overview-hero flex items-center justify-between gap-6 p-8"><div><span className="workspace-hero-eyebrow">Statutory Profile</span><h1>IEC Applications</h1><p>Create, continue, and track DGFT Importer Exporter Code applications.</p></div><button onClick={onCreate} disabled={saving} className="workspace-hero-primary"><Plus size={17}/>New IEC Application</button></section><section className="dashboard-panel overflow-hidden"><header className="iec-list-header"><div><p className="workspace-hero-eyebrow">Application register</p><h2>IEC Dashboard</h2></div></header><div className="iec-table-wrap"><table className="admin-register-table"><thead><tr><th>Application ID</th><th>Firm / PAN</th><th>Application Type</th><th>Submitted</th><th>Last Updated</th><th>Status</th><th>Action</th></tr></thead><tbody>{applications.length?applications.map(a=><tr key={a.id}><td><b>{a.request_code}</b><small>{a.iec_number||"IEC pending"}</small></td><td><b>{a.firm_details?.firmName||"Draft application"}</b><small>{a.firm_details?.pan||"PAN pending"}</small></td><td>{label(a.application_type)}</td><td>{a.submitted_at?new Date(a.submitted_at).toLocaleDateString("en-IN"):"—"}</td><td>{new Date(a.updated_at).toLocaleString("en-IN")}</td><td><span className={`iec-status ${statusClass[a.status]}`}>{label(a.status)}</span></td><td><button className="iec-action" onClick={()=>onOpen(a.id)}>{a.status==="DRAFT"?"Continue":"View"}<ArrowRight size={14}/></button></td></tr>):<tr><td colSpan="7" className="iec-empty"><FileText/><b>No IEC applications yet</b><span>Start a new application and save it as a draft.</span></td></tr>}</tbody></table></div></section></div>}
function Hero({application,onBack}){return <section className="workspace-overview-hero iec-application-hero flex items-center justify-between gap-5 p-7"><div><button onClick={onBack} className="iec-back"><ArrowLeft size={15}/>IEC Dashboard</button><span className="workspace-hero-eyebrow">{application.request_code}</span><h1>IEC Application</h1><p>DGFT statutory profile · progress saves between steps</p></div><span className={`iec-status ${statusClass[application.status]}`}>{label(application.status)}</span></section>}
function Stepper({step,setStep}){return <nav className="iec-stepper">{steps.map((name,i)=><button key={name} onClick={()=>setStep(i+1)} className={step===i+1?"active":step>i+1?"done":""}><span>{step>i+1?<Check size={14}/>:i+1}</span><b>{name}</b></button>)}</nav>}
const Input=({label:caption,required,...props})=><label className="iec-field"><span>{caption}{required&&<i>*</i>}</span><input {...props}/></label>;
const Select=({label:caption,options,required,...props})=><label className="iec-field"><span>{caption}{required&&<i>*</i>}</span><select {...props}>{options.map(o=><option key={o} value={o}>{o||"Select"}</option>)}</select></label>;
const YesNo=({label:caption,value,onChange,na=false,disabled})=><Select label={caption} value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} options={na?["YES","NO","NA"]:["YES","NO"]}/>;
const bind=(value,set,key)=>({value:value[key]||"",onChange:e=>set({...value,[key]:e.target.value})});
function Section({title,subtitle,children}){return <><header className="iec-section-title"><h2>{title}</h2><p>{subtitle}</p></header><div className="iec-grid">{children}</div></>}
function FileUpload({onChange,disabled}){return <label className="iec-upload"><Upload size={18}/><span>Upload PDF, JPG or PNG</span><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={onChange} disabled={disabled}/></label>}
function FirmSection({value,set,readonly,onUpload}){return <Section title="Firm Details" subtitle="Legal identity and exporter classification"><Input label="Firm Name" required {...bind(value,set,"firmName")} disabled={readonly}/><Select label="Nature of Concern / Firm" required {...bind(value,set,"nature")} disabled={readonly} options={["","Proprietorship","Partnership","Private Limited","Public Limited","LLP","Trust","HUF","Others"]}/>{value.nature==="Others"&&<Input label="Nature of Firm (Others)" {...bind(value,set,"natureOther")} disabled={readonly}/>}<Select label="Category of Exporters" required {...bind(value,set,"exporterCategory")} disabled={readonly} options={["","Merchant Exporter","Manufacturer Exporter","Service Provider","Others"]}/>{value.exporterCategory==="Others"&&<Input label="Exporter Category (Others)" {...bind(value,set,"categoryOther")} disabled={readonly}/>}<Input label="PAN" required maxLength="10" {...bind(value,set,"pan")} onChange={e=>set({...value,pan:e.target.value.toUpperCase()})} disabled={readonly}/><Input label="Name as PAN Card" required {...bind(value,set,"panName")} disabled={readonly}/><Input label="Date of Birth / Incorporation" type="date" required {...bind(value,set,"birthDate")} disabled={readonly}/><Input label="CIN" {...bind(value,set,"cin")} disabled={readonly}/><YesNo label="Do you have GSTIN?" value={value.hasGstin} onChange={v=>set({...value,hasGstin:v,gstin:v==="NO"?"":value.gstin})} disabled={readonly}/>{value.hasGstin==="YES"&&<Input label="GSTIN" maxLength="15" {...bind(value,set,"gstin")} onChange={e=>set({...value,gstin:e.target.value.toUpperCase()})} disabled={readonly}/>}<YesNo label="Located in SEZ?" value={value.sez} onChange={v=>set({...value,sez:v})} disabled={readonly}/><Input label="Contact Number" required inputMode="numeric" maxLength="10" {...bind(value,set,"contact")} disabled={readonly}/><Input label="Email ID" required type="email" {...bind(value,set,"email")} disabled={readonly}/>{["eou","ehtp","stp","btp"].map(k=><YesNo key={k} label={`Located in ${k.toUpperCase()}?`} value={value[k]} onChange={v=>set({...value,[k]:v})} na disabled={readonly}/>)}<FileUpload onChange={onUpload} disabled={readonly}/></Section>}
function AddressSection({value,set,readonly,onUpload}){return <Section title="Registered Office Address" subtitle="DGFT jurisdiction and registered premises"><Input label="Address Line 1" required {...bind(value,set,"address1")} disabled={readonly}/><Input label="Address Line 2" {...bind(value,set,"address2")} disabled={readonly}/><Input label="City" required {...bind(value,set,"city")} disabled={readonly}/><Input label="District" {...bind(value,set,"district")} disabled={readonly}/><Input label="State" required {...bind(value,set,"state")} disabled={readonly}/><Input label="Pincode" required maxLength="6" {...bind(value,set,"pincode")} disabled={readonly}/><Input label="DGFT Office" {...bind(value,set,"dgftOffice")} disabled={readonly}/><FileUpload onChange={onUpload} disabled={readonly}/></Section>}
function RepeatSection({type,title,items,value,set,empty,editing,setEditing,onSave,onDelete,readonly}){const branch=type==="branches";return <><Section title={title} subtitle={`Add and manage multiple ${branch?"branches":"authorized persons"}`}><Input label={branch?"Branch Code":"Name"} required {...bind(value,set,branch?"branchCode":"name")} disabled={readonly}/>{branch?<><YesNo label="Is it SEZ?" value={value.sez} onChange={v=>set({...value,sez:v})} disabled={readonly}/><YesNo label="Is it EOU?" value={value.eou} onChange={v=>set({...value,eou:v})} disabled={readonly}/><YesNo label="Active Branch?" value={value.active} onChange={v=>set({...value,active:v})} disabled={readonly}/><YesNo label="Have GSTIN?" value={value.hasGstin} onChange={v=>set({...value,hasGstin:v})} disabled={readonly}/>{value.hasGstin==="YES"&&<Input label="GSTIN" {...bind(value,set,"gstin")} disabled={readonly}/>}</>:<><Input label="DIN" {...bind(value,set,"din")} disabled={readonly}/><YesNo label="Foreign Director?" value={value.foreignDirector} onChange={v=>set({...value,foreignDirector:v})} disabled={readonly}/>{value.foreignDirector==="YES"&&<Input label="Passport Number" {...bind(value,set,"passport")} disabled={readonly}/>}<Input label="Name as PAN" {...bind(value,set,"panName")} disabled={readonly}/><Input label="PAN" {...bind(value,set,"pan")} disabled={readonly}/><Input label="Date of Birth" type="date" {...bind(value,set,"birthDate")} disabled={readonly}/><Input label="Title" {...bind(value,set,"title")} disabled={readonly}/><Input label="Father Name" {...bind(value,set,"fatherName")} disabled={readonly}/><Input label="Mobile No." {...bind(value,set,"mobile")} disabled={readonly}/></>} {["address1","address2","city","district","state","pincode"].map(k=><Input key={k} label={label(k)} {...bind(value,set,k)} disabled={readonly}/>)}</Section>{!readonly&&<div className="iec-repeat-actions"><button onClick={()=>onSave(type)} className="primary"><Plus size={15}/>{editing.type===type?"Update":"Add"} {branch?"Branch":"Person"}</button>{editing.type===type&&<button onClick={()=>{set(empty);setEditing({type:"",id:null});}}><X size={15}/>Cancel</button>}</div>}<div className="iec-summary-grid">{items.map(item=><article key={item.id}><div><b>{branch?item.branch_code:item.name}</b><span>{branch?`${item.details.city||"—"}, ${item.details.state||"—"} - ${item.details.pincode||"—"}`:`${item.details.pan||item.details.passport||"Identity pending"} · ${item.details.mobile||"Mobile pending"}`}</span></div><div>{!readonly&&<><button onClick={()=>{set({...empty,...item.details,[branch?"branchCode":"name"]:branch?item.branch_code:item.name});setEditing({type,id:item.id});}}><Pencil size={14}/>Edit</button><button className="danger" onClick={()=>onDelete(type,item.id)}><Trash2 size={14}/>Delete</button></>}</div></article>)}</div></>}
function BankSection({value,set,readonly}){return <Section title="Bank Information" subtitle="Primary account for IEC verification"><Input label="Account Number" required {...bind(value,set,"accountNumber")} disabled={readonly}/><Input label="Account Holder Name" required {...bind(value,set,"accountHolder")} disabled={readonly}/><Input label="IFSC Code" required {...bind(value,set,"ifsc")} onChange={e=>set({...value,ifsc:e.target.value.toUpperCase()})} disabled={readonly}/><Input label="Bank Name" {...bind(value,set,"bankName")} disabled={readonly}/><Input label="Branch Address" {...bind(value,set,"branchAddress")} disabled={readonly}/><YesNo label="Is Primary?" value={value.primary} onChange={v=>set({...value,primary:v})} disabled={readonly}/><div className="iec-field"><span>Validation Status</span><b className="iec-validation">{label(value.validationStatus)}</b></div></Section>}
function TradeSection({value,set,readonly}){return <Section title="Other Details" subtitle="Import and export activity categories">{Object.keys(emptyTrade).map(k=><Input key={k} label={label(k)} placeholder="Select or enter activity category" {...bind(value,set,k)} disabled={readonly}/>)}</Section>}
const declarationsText=["The entity confirms it has not been penalized under the Customs, Central Excise, FTDR, FEMA or COFEPOSA Acts and applicable persons are not on the Denied Entity List.","The entity has not obtained or applied for another IEC for its registered/head office through another Licensing Authority.","The applicant undertakes to abide by the FTDR Act, Rules, Orders, Foreign Trade Policy, Handbook of Procedures and ITC (HS).","The applicant understands that incorrect or false information may result in penal action or other legal consequences.","All particulars and statements in this application are true and correct to the best of the applicant’s knowledge.","The applicant is authorized to verify and sign this declaration under the Foreign Trade Policy."];
function DeclarationSection({value,set,readonly}){return <><Section title="Declaration Details" subtitle="Every statutory declaration is mandatory">{declarationsText.map((text,i)=><label key={text} className="iec-declaration"><input type="checkbox" checked={!!value[`declaration${i+1}`]} onChange={e=>set({...value,[`declaration${i+1}`]:e.target.checked})} disabled={readonly}/><span><b>Declaration {i+1}</b>{text}</span></label>)}<label className="iec-declaration terms"><input type="checkbox" checked={!!value.terms} onChange={e=>set({...value,terms:e.target.checked})} disabled={readonly}/><span><b>Terms & Conditions</b>I agree to the Terms & Conditions.</span></label><Input label="Place" required {...bind(value,set,"place")} disabled={readonly}/><Input label="Request Submitted Date" value={new Date().toLocaleDateString("en-IN")} disabled/></Section></>}
function Review({application,data,setStep,onDownload,onDelete,readonly}){const sections=[["Firm Details",data.firm,1],["Registered Address",data.address,2],["Bank Information",data.bank,5],["Import / Export Details",data.trade,6],["Declarations",data.declarations,7]];return <><header className="iec-section-title"><h2>Review Application</h2><p>Verify every section before final submission.</p></header><div className="iec-review">{sections.map(([title,values,target])=><article key={title}><header><h3>{title}</h3><button onClick={()=>setStep(target)}><Pencil size={14}/>Edit</button></header><dl>{Object.entries(values).map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd>{typeof v==="boolean"?(v?"Accepted":"Not accepted"):(v||"—")}</dd></div>)}</dl></article>)}<article><header><h3>Branches ({application.branches.length})</h3><button onClick={()=>setStep(3)}><Pencil size={14}/>Edit</button></header></article><article><header><h3>Persons / Directors ({application.persons.length})</h3><button onClick={()=>setStep(4)}><Pencil size={14}/>Edit</button></header></article><article><header><h3>Uploaded Documents ({application.documents.length})</h3></header><div className="iec-documents">{application.documents.map(d=><div key={d.id}><FileText size={16}/><span>{d.original_name}<small>{label(d.section)}</small></span><button onClick={()=>onDownload(d)}><Eye size={14}/></button>{!readonly&&<button onClick={()=>onDelete(d)}><Trash2 size={14}/></button>}</div>)}</div></article></div></>}
