import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { Activity, ArrowLeft, ArrowRight, Calculator, CheckCircle2, Download, Equal, FileText, Fingerprint, LoaderCircle, PlusCircle, Receipt, RefreshCw, Save, Star, Trash2, Trophy, Upload, X, Zap } from "lucide-react";
import { downloadLicensingDocument, getLicensingConfiguration, getLicensingLedger, getLicensingQuote, getLicensingRequests, removeLicensingDocument, saveLicensingDraft, submitLicensingRequest, uploadLicensingDocument } from "../../services/licensingService";

const SLUG = "star-export-house";
const THRESHOLDS = { "1": 3, "2": 15, "3": 50, "4": 200, "5": 800 };
const money = (value) => new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(Number(value || 0));
const errorText = (error, fallback) => error?.response?.data?.message || error?.message || fallback;
const keyOf = (item) => item?.document_key || item?.documentKey || "";
const nameOf = (item) => item?.original_name || item?.name || "Uploaded document";

export default function StarExportHouseWorkflow({ onBack }) {
  const navigate = useNavigate(); const fileInputs = useRef({});
  const [configuration, setConfiguration] = useState(null); const [entity, setEntity] = useState({});
  const [draft, setDraft] = useState(null); const [form, setForm] = useState({ starRating: "1", iecNumber: "", fobValue: "", isMsme: "false" });
  const [documents, setDocuments] = useState([]); const [quote, setQuote] = useState(null); const [ledger, setLedger] = useState(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState("");

  useEffect(() => { let active = true; Promise.all([getLicensingConfiguration(SLUG), getLicensingRequests(SLUG), getLicensingLedger(SLUG)]).then(async ([configData, requestData, ledgerData]) => {
    const restored = requestData.requests?.find((item) => item.status === "DRAFT"); const nextForm = { starRating: "1", iecNumber: configData.clientContext?.iecNumber || "", fobValue: "", isMsme: "false", ...(restored?.payload?.form || {}) };
    const nextQuote = await getLicensingQuote(SLUG, nextForm); if (!active) return; setConfiguration(configData.service); setEntity(configData.clientContext || {}); setDraft(restored || null); setForm(nextForm); setDocuments(restored?.documents || []); setQuote(nextQuote); setLedger(ledgerData);
  }).catch((error) => Swal.fire("Unable to load Star Export House", errorText(error, "Please try again shortly."), "error")).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);

  const metrics = useMemo(() => { const actual = Number(form.fobValue) || 0; const multiplier = form.starRating === "1" && form.isMsme === "true" ? 2 : 1; const effective = actual * multiplier; const threshold = THRESHOLDS[form.starRating] || 0; return { actual, multiplier, effective, threshold, eligible: actual > 0 && effective >= threshold, deficit: Math.max(0, threshold - effective) }; }, [form]);
  const documentRules = useMemo(() => [{ id: "caStatement", label: "CA Certified Performance Statement", required: true }, { id: "annexure1A", label: "Annexure 1A – Detailed Shipping Bill Matrix", required: true }, ...(form.isMsme === "true" && form.starRating === "1" ? [{ id: "msmeCert", label: "MSME / Udyam Certificate", required: true }] : [])], [form.isMsme, form.starRating]);
  async function updateField(field, value) { const next = { ...form, [field]: value }; if (field === "starRating" && value !== "1") next.isMsme = "false"; setForm(next); try { setQuote(await getLicensingQuote(SLUG, next)); } catch { setQuote(null); } }
  function validationMessage() { if (!THRESHOLDS[form.starRating]) return "Select a valid certification level."; if (metrics.actual <= 0) return "Enter the FOB export performance in USD million."; if (!metrics.eligible) return `Effective FOB value is USD ${metrics.deficit.toFixed(2)} million below the ${form.starRating}-Star threshold.`; const uploaded = new Set(documents.map(keyOf)); const missing = documentRules.find((item) => item.required && !uploaded.has(item.id)); return missing ? `Upload the required document: ${missing.label}.` : ""; }
  async function persistDraft(showMessage = true) { const response = await saveLicensingDraft(SLUG, { requestId: draft?.id, form }); setDraft(response.request); if (showMessage) await Swal.fire({ icon: "success", title: "Performance audit saved", text: `${response.request.request_code} can be resumed later.`, confirmButtonColor: "#2952ff" }); return response.request; }
  async function saveDraft() { try { setBusy(true); await persistDraft(); } catch (error) { Swal.fire("Unable to save audit", errorText(error, "Please try again."), "error"); } finally { setBusy(false); } }
  async function uploadDocument(key, event) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; try { setUploading(key); const request = draft || await persistDraft(false); const response = await uploadLicensingDocument(SLUG, request.id, key, file); setDocuments((current) => [...current.filter((item) => keyOf(item) !== key), response.document]); } catch (error) { Swal.fire("Upload failed", errorText(error, "The document could not be uploaded."), "error"); } finally { setUploading(""); } }
  async function removeDocument(key) { if (!draft) return; try { setUploading(key); await removeLicensingDocument(SLUG, draft.id, key); setDocuments((current) => current.filter((item) => keyOf(item) !== key)); } catch (error) { Swal.fire("Unable to remove file", errorText(error, "Please try again."), "error"); } finally { setUploading(""); } }
  async function downloadDocument(key, name) { try { await downloadLicensingDocument(SLUG, draft.id, key, name); } catch (error) { Swal.fire("Unable to download file", errorText(error, "Please try again."), "error"); } }
  async function submit() { const missing = validationMessage(); if (missing) return Swal.fire({ icon: "error", title: "Status application is incomplete", text: missing, confirmButtonColor: "#2952ff" }); try { setBusy(true); const request = await persistDraft(false); const response = await submitLicensingRequest(SLUG, { requestId: request.id, form }); setLedger(await getLicensingLedger(SLUG)); window.dispatchEvent(new CustomEvent("wallet:updated", { detail: { balance: response.balances?.walletBalance, creditLine: response.balances?.creditLineBalance } })); await Swal.fire({ icon: "success", title: "Star Export House application submitted", text: `${response.request.request_code} has been sent to the admin team.`, confirmButtonColor: "#2952ff" }); onBack(); } catch (error) { if (error.response?.status === 402) { const result = await Swal.fire({ icon: "warning", title: "Top up required", text: "Your Wallet or Credit Line balance is insufficient.", showCancelButton: true, confirmButtonText: "Go to Wallet & Credit", confirmButtonColor: "#2952ff" }); if (result.isConfirmed) navigate("/client/wallet-credit#add-credit"); } else Swal.fire("Unable to submit application", errorText(error, "Please verify the audit and try again."), "error"); } finally { setBusy(false); } }

  if (loading || !configuration) return <div className="flex min-h-[520px] items-center justify-center text-slate-500"><LoaderCircle className="mr-2 animate-spin" /> Loading Star Export House…</div>;
  const valid = !validationMessage(); const price = quote || {}; const balances = ledger?.balances || {};
  return <section className="mx-auto max-w-[1370px] animate-in fade-in duration-300"><div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.08)]">
    <header className="flex items-start justify-between border-b px-5 py-5 md:px-7"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#2952ff] text-white shadow-lg shadow-blue-100"><Trophy /></div><div><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} /> Back to Service Store</button><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black uppercase">Star Export House Status</h1><span className="rounded-full bg-slate-900 px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-white">FTP 2023</span></div><p className="mt-1 flex flex-wrap items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-500"><Fingerprint size={11} className="text-[#2952ff]" />{draft?.request_code || "Reference generated on save"}<Zap size={11} className="text-amber-500" /> 48-hour post-audit SLA</p></div></div><button onClick={onBack} aria-label="Close workflow"><X className="text-slate-400" /></button></header>
    <div className="flex flex-wrap items-center justify-between gap-2 border-b bg-blue-50/70 px-5 py-3 text-[10px] font-black uppercase tracking-[.14em] text-blue-700"><span className="flex items-center gap-2"><RefreshCw size={12} /> Profile: {entity.companyName || "Company"}{form.iecNumber ? ` · IEC ${form.iecNumber}` : ""}</span><span>RCMC verification required</span></div>
    <div className="grid gap-6 p-5 xl:grid-cols-[minmax(0,1.4fr)_360px] md:p-7"><div className="space-y-6">
      <div><p className="mb-3 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">Target certification level</p><div className="grid grid-cols-5 gap-2 rounded-2xl border bg-slate-100 p-1">{Object.keys(THRESHOLDS).map((level) => <button key={level} onClick={() => updateField("starRating", level)} className={`flex flex-col items-center rounded-xl py-3 text-[10px] font-black ${form.starRating === level ? "border border-blue-200 bg-white text-[#2952ff] shadow-sm" : "text-slate-400"}`}><Star size={16} fill={form.starRating === level ? "currentColor" : "none"} /><span className="mt-1">{level} Star</span></button>)}</div></div>
      <div className="grid gap-4 md:grid-cols-2"><Field label="Actual FOB Value (USD Million)" icon={<Activity size={12} />} required><input type="number" min="0" step="0.01" value={form.fobValue} onChange={(e) => updateField("fobValue", e.target.value)} placeholder="Total export performance" /></Field><div><p className="mb-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">Weightage eligibility</p><button type="button" disabled={form.starRating !== "1"} onClick={() => updateField("isMsme", form.isMsme === "true" ? "false" : "true")} className={`flex w-full items-center justify-between rounded-xl border-2 p-3 text-left ${form.starRating !== "1" ? "cursor-not-allowed bg-slate-50 opacity-50" : form.isMsme === "true" ? "border-blue-200 bg-blue-50" : "border-slate-200 bg-white"}`}><span><b className="block text-[10px] uppercase">Double weightage</b><small className="text-[9px] text-slate-500">MSME / Startup incentive for 1-Star</small></span><span className={`relative h-5 w-10 rounded-full ${form.isMsme === "true" ? "bg-[#2952ff]" : "bg-slate-200"}`}><i className={`absolute top-1 h-3 w-3 rounded-full bg-white transition-all ${form.isMsme === "true" ? "left-6" : "left-1"}`} /></span></button></div></div>
      {metrics.actual > 0 && <div className={`rounded-2xl border-2 p-5 ${metrics.eligible ? "border-emerald-200 bg-emerald-50" : "border-rose-200 bg-rose-50"}`}><div className="flex items-center justify-between border-b border-black/5 pb-3"><span className="flex items-center gap-2 text-[11px] font-black uppercase tracking-widest"><Calculator size={18} /> Performance audit</span><b className={`rounded-full px-3 py-1 text-[9px] uppercase text-white ${metrics.eligible ? "bg-emerald-600" : "bg-rose-600"}`}>{metrics.eligible ? "Target met" : "Target deficient"}</b></div><div className="mt-4 space-y-3 text-xs font-bold"><MathRow icon={<Activity size={14} />} label="Actual FOB performance" value={`$${metrics.actual.toFixed(2)}M`} />{metrics.multiplier === 2 && <MathRow icon={<PlusCircle size={14} />} label="MSME double-weightage bonus" value={`+$${metrics.actual.toFixed(2)}M`} accent />}<MathRow icon={<Equal size={14} />} label="Effective audit value" value={`$${metrics.effective.toFixed(2)}M`} strong /></div><div className="mt-4 flex justify-between border-t border-dashed border-black/10 pt-4 text-xs"><span>Threshold for {form.starRating}-Star: <b>${metrics.threshold}M</b></span>{!metrics.eligible && <span className="text-rose-600">Shortfall: <b>${metrics.deficit.toFixed(2)}M</b></span>}</div></div>}
      <div><h2 className="mb-3 text-[11px] font-black uppercase tracking-[.18em] text-slate-800">Statutory evidence</h2><div className="space-y-2">{documentRules.map((item) => { const saved = documents.find((doc) => keyOf(doc) === item.id); return <article key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3 hover:border-blue-300"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${saved ? "bg-emerald-50 text-emerald-600" : "bg-slate-50 text-slate-400"}`}>{saved ? <CheckCircle2 size={20} /> : <FileText size={20} />}</div><div className="min-w-0 flex-1"><b className="block text-xs">{item.label}<em className="ml-2 not-italic text-[9px] uppercase text-rose-500">Required</em></b><span className={`block truncate text-[10px] ${saved ? "text-emerald-600" : "text-slate-400"}`}>{saved ? nameOf(saved) : "PDF, DOC, XLS, JPG or PNG · maximum 20 MB"}</span></div>{saved && <><button onClick={() => downloadDocument(item.id, nameOf(saved))} className="rounded-lg p-2 text-[#2952ff]" aria-label={`Download ${item.label}`}><Download size={16} /></button><button onClick={() => removeDocument(item.id)} className="rounded-lg p-2 text-rose-500" aria-label={`Remove ${item.label}`}><Trash2 size={16} /></button></>}<button onClick={() => fileInputs.current[item.id]?.click()} disabled={Boolean(uploading)} className="rounded-lg border bg-white px-4 py-2 text-[10px] font-black uppercase disabled:opacity-50"><Upload className="mr-1 inline" size={14} />{uploading === item.id ? "Uploading" : saved ? "Replace" : "Upload"}</button><input ref={(node) => { fileInputs.current[item.id] = node; }} type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={(event) => uploadDocument(item.id, event)} /></article>; })}</div></div>
    </div><aside className="h-fit overflow-hidden rounded-3xl bg-slate-950 text-white shadow-xl xl:sticky xl:top-24"><div className="flex items-center gap-2 border-b border-white/10 p-5 text-blue-400"><Receipt size={16} /><span className="text-[10px] font-black uppercase tracking-[.2em]">Application Ledger</span></div><div className="space-y-4 p-5"><Ledger label="DGFT portal fee" value={price.officialFee} /><Ledger label="Performance audit & drafting" value={price.draftingFee} /><Ledger label="GST (18%)" value={price.gst} /><div className="border-t border-white/10 pt-3 text-xs text-slate-400"><p>Wallet after: <b className="float-right text-white">₹{money(price.closingWalletBalance)}</b></p><p className="mt-2">Credit line after: <b className="float-right text-white">₹{money(price.availableCreditAfter)}</b></p></div><div className="rounded-2xl bg-[#2952ff] p-4"><p className="text-[9px] font-black uppercase tracking-widest text-blue-100">Total application charge</p><p className="mt-1 text-3xl font-black">₹{money(price.total)}</p></div><p className="text-[10px] text-slate-500">Balances: Wallet ₹{money(balances.walletBalance)} · Credit ₹{money(balances.creditLineBalance)}</p></div></aside></div>
    <footer className="flex flex-col justify-between gap-3 border-t bg-slate-50 p-5 sm:flex-row"><button onClick={onBack} className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Discard</button><div className="flex flex-col gap-3 sm:flex-row"><button onClick={saveDraft} disabled={busy || Boolean(uploading)} className="flex items-center justify-center gap-2 rounded-xl border bg-white px-6 py-3 text-sm font-bold disabled:opacity-50"><Save size={16} /> Save Draft</button><button onClick={submit} disabled={busy || Boolean(uploading)} className={`flex items-center justify-center gap-2 rounded-xl px-7 py-3 text-sm font-black disabled:opacity-50 ${valid ? "bg-[#2952ff] text-white" : "border bg-slate-100 text-slate-500"}`}>{valid ? "Confirm Audit & Process" : metrics.actual && !metrics.eligible ? "Performance Deficit" : "Complete Requirements"}<ArrowRight size={16} /></button></div></footer>
  </div></section>;
}

function Field({ label, required = false, icon = null, children }) { return <label className="block"><span className="mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{icon}{label}{required && <em className="not-italic text-rose-500">*</em>}</span><span className="iem-field-control block">{children}</span></label>; }
function MathRow({ icon, label, value, accent = false, strong = false }) { return <div className={`flex items-center justify-between ${accent ? "text-[#2952ff]" : "text-slate-700"}`}><span className="flex items-center gap-2">{icon}{label}</span><b className={strong ? "text-base text-slate-950" : ""}>{value}</b></div>; }
function Ledger({ label, value }) { return <div className="flex items-center justify-between gap-3 text-xs"><span className="text-slate-400">{label}</span><b className="text-rose-400">− ₹{money(value)}</b></div>; }
