import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { AlertTriangle, ArrowLeft, ArrowRight, FileText, PackageCheck, Receipt, Save, Upload, Wallet, X, Zap } from "lucide-react";
import { getUnIipConfiguration, getUnIipLedger, getUnIipQuote, getUnIipRequests, removeUnIipDocument,
  saveUnIipDraft, submitUnIip, uploadUnIipDocument } from "../../services/unIipService";

const emptyFile = { status: "Not Uploaded", name: null };
export default function UnIipPackagingAuditWorkflow({ service, onBack }) {
  const navigate = useNavigate();
  const [configuration, setConfiguration] = useState(null); const [quote, setQuote] = useState(null);
  const [ledger, setLedger] = useState({ transactions: [] }); const [requestId, setRequestId] = useState(null);
  const [draftCode, setDraftCode] = useState(""); const [requestType, setRequestType] = useState("new");
  const [form, setForm] = useState({ shippingName: "", unNumber: "", hazardClass: "9", packagingGroup: "III",
    grossWeight: "", dimensionLength: "", dimensionWidth: "", stitchesPerDm: "" });
  const [files, setFiles] = useState({}); const [initializing, setInitializing] = useState(true);
  const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState("");
  const [quoteLoading, setQuoteLoading] = useState(false); const [error, setError] = useState("");
  const skipQuote = useRef(false);
  const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));

  useEffect(() => { let active = true;
    Promise.all([getUnIipConfiguration(), getUnIipRequests(), getUnIipLedger()]).then(async ([config, requests, ledgerData]) => {
      const draft = requests.requests?.find((item) => item.status === "DRAFT"); const body = draft?.payload || {};
      const type = body.requestType || "new"; const quoteData = await getUnIipQuote(type); if (!active) return;
      const restored = Object.fromEntries((config.service.documents || []).map((item) => [item.id, { ...emptyFile }]));
      for (const document of draft?.documents || []) restored[document.documentKey] = { status: "Uploaded", name: document.name, size: Number(document.size || 0) };
      setConfiguration(config); setLedger(ledgerData); setQuote(quoteData); skipQuote.current = true; setRequestType(type);
      setRequestId(draft?.id || null); setDraftCode(draft?.request_code || ""); setFiles(restored);
      setForm((current) => ({ ...current, shippingName: body.shippingName || "", unNumber: body.unNumber || "",
        hazardClass: body.hazardClass || "9", packagingGroup: body.packagingGroup || "III", grossWeight: body.grossWeight || "",
        dimensionLength: body.dimensionLength || "", dimensionWidth: body.dimensionWidth || "", stitchesPerDm: body.stitchesPerDm || "" }));
    }).catch(() => active && setError("Unable to load UN IIP Packaging Audit."))
      .finally(() => active && setInitializing(false)); return () => { active = false; }; }, []);
  useEffect(() => { if (initializing) return; if (skipQuote.current) { skipQuote.current = false; return; }
    setQuoteLoading(true); getUnIipQuote(requestType).then(setQuote).catch(() => setError("Unable to calculate packaging audit pricing."))
      .finally(() => setQuoteLoading(false)); }, [requestType, initializing]);

  const config = configuration?.service;
  const documents = useMemo(() => (config?.documents || []).filter((item) => !item.requestTypes || item.requestTypes.includes(requestType)), [config, requestType]);
  const payload = () => ({ requestId, requestType, ...form, documents: files });
  const valid = Boolean(form.shippingName && /^\d{4}$/.test(form.unNumber) && form.hazardClass && form.packagingGroup &&
    Number(form.grossWeight) > 0 && Number(form.dimensionLength) > 0 && Number(form.dimensionWidth) > 0 && Number(form.stitchesPerDm) > 0 &&
    documents.filter((item) => item.required).every((item) => files[item.id]?.status === "Uploaded"));
  async function ensureDraft() { if (requestId) return requestId; const data = await saveUnIipDraft(payload()); setRequestId(data.request.id); setDraftCode(data.request.request_code); return data.request.id; }
  async function selectFile(key, event) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return;
    try { setUploading(key); const id = await ensureDraft(); const data = await uploadUnIipDocument(id, key, file); setFiles((current) => ({ ...current, [key]: { status: "Uploaded", name: data.document.name, size: data.document.size } })); }
    catch (e) { Swal.fire("Upload failed", e.response?.data?.message || "The document could not be uploaded.", "error"); } finally { setUploading(""); } }
  async function removeFile(key) { if (!requestId) return; try { setUploading(key); await removeUnIipDocument(requestId, key); setFiles((current) => ({ ...current, [key]: { ...emptyFile } })); } catch (e) { Swal.fire("Unable to remove document", e.response?.data?.message || "Please try again.", "error"); } finally { setUploading(""); } }
  async function saveDraft() { try { setBusy(true); const data = await saveUnIipDraft(payload()); setRequestId(data.request.id); setDraftCode(data.request.request_code); await Swal.fire({ icon: "success", title: "Packaging audit draft saved", text: `${data.request.request_code} can be resumed later.`, confirmButtonColor: "#2952ff" }); } catch (e) { Swal.fire("Unable to save draft", e.response?.data?.message || "Please try again.", "error"); } finally { setBusy(false); } }
  async function submit() { if (!valid) return; try { setBusy(true); const data = await submitUnIip(payload()); const [nextQuote, nextLedger] = await Promise.all([getUnIipQuote(requestType), getUnIipLedger()]); setQuote(nextQuote); setLedger(nextLedger); window.dispatchEvent(new CustomEvent("wallet:updated", { detail: { balance: data.balances.walletBalance, creditLine: data.balances.creditLineBalance } })); await Swal.fire({ icon: "success", title: "Packaging audit submitted", text: `${data.request.request_code} has been sent to the admin team.`, confirmButtonColor: "#2952ff" }); onBack(); }
    catch (e) { if (e.response?.status === 402) { const code = e.response?.data?.errors?.code; const message = code === "INSUFFICIENT_WALLET" ? "Wallet balance is insufficient. Please top up your Wallet." : code === "INSUFFICIENT_CREDIT_LINE" ? "Credit Line balance is insufficient. Please top up your Credit Line." : "Wallet and Credit Line balances are insufficient. Please top up both."; const result = await Swal.fire({ icon: "warning", title: "Top up required", text: message, showCancelButton: true, confirmButtonText: "Go to Wallet & Credit", confirmButtonColor: "#2952ff" }); if (result.isConfirmed) navigate("/client/wallet-credit#add-credit"); } else Swal.fire("Unable to submit packaging audit", e.response?.data?.message || "Please try again.", "error"); } finally { setBusy(false); } }
  if (initializing) return <div className="mx-auto max-w-7xl p-6"><div className="min-h-[700px] animate-pulse rounded-[30px] bg-white shadow-lg" /></div>;
  const costs = quote || {}; const dropHeight = form.packagingGroup === "III" ? "0.80 m" : "1.20 m";
  return <div className="min-h-[calc(100vh-7rem)]"><div className="mx-auto max-w-7xl px-4 py-4 lg:px-6">
    {error && <div className="mb-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}
    {draftCode && <div className="mb-3 flex gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-3 text-blue-900"><Save size={17}/><div><b className="text-xs">Draft {draftCode} restored</b><p className="text-[11px] text-blue-600">Continue your packaging audit request.</p></div></div>}
    <div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.08)]">
      <header className="flex justify-between border-b p-5"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#2952ff] text-white"><PackageCheck/></div><div><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Back to Compliance</button><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black uppercase">{config?.name || service.title}</h1><span className="rounded-full bg-slate-900 px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-white">{config?.transactionType}</span></div><p className="mt-1 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">{config?.standard}<Zap size={11} className="text-amber-500"/> Priority audit</p></div></div><button onClick={onBack}><X className="text-slate-400"/></button></header>
      <div className="grid gap-5 p-5 xl:grid-cols-[minmax(0,1.45fr)_360px]"><div className="space-y-5">
        <div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-1">{(config?.requestTypes || []).map((type) => <button key={type.id} onClick={() => setRequestType(type.id)} className={`rounded-xl px-3 py-3 ${requestType === type.id ? "border border-blue-200 bg-white text-[#2952ff] shadow-sm" : "text-slate-400"}`}><b className="block text-xs uppercase">{type.label}</b><span className="text-[9px] uppercase">{type.description}</span></button>)}</div>
        <div className="grid gap-3 md:grid-cols-2"><Field label="Proper Shipping Name"><input value={form.shippingName} onChange={update("shippingName")} placeholder="Enter regulated cargo name"/></Field><Field label="UN Number (4-digit)"><input maxLength={4} value={form.unNumber} onChange={update("unNumber")} placeholder="E.g. 2216"/></Field><Field label="Hazard Class"><select value={form.hazardClass} onChange={update("hazardClass")}>{(config?.hazardClasses || []).map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></Field><Field label="Packaging Group"><select value={form.packagingGroup} onChange={update("packagingGroup")}>{(config?.packagingGroups || []).map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></Field><Field label="Gross / Net Mass (kg)"><input type="number" min="0" value={form.grossWeight} onChange={update("grossWeight")} placeholder="Enter mass"/></Field><Field label="Package Dimensions (cm)"><span className="grid grid-cols-2 gap-2"><input type="number" min="0" value={form.dimensionLength} onChange={update("dimensionLength")} placeholder="Length"/><input type="number" min="0" value={form.dimensionWidth} onChange={update("dimensionWidth")} placeholder="Width"/></span></Field><Field label="Stitches per dm"><input type="number" min="0" value={form.stitchesPerDm} onChange={update("stitchesPerDm")} placeholder="Enter stitch density"/></Field><Field label="Audit Laboratory"><input readOnly value={config?.labCenter || "Assigned by IIP"}/></Field></div>
        <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-800"><AlertTriangle size={18}/><p className="text-[11px] font-semibold">Required drop-test height for Packaging Group {form.packagingGroup}: <b>{dropHeight}</b>. Final testing remains subject to IIP laboratory standards.</p></div>
        <div><h2 className="mb-3 flex items-center gap-2 text-[11px] font-black uppercase tracking-[.18em]"><Upload size={14}/> Required packaging evidence</h2><div className="space-y-2">{documents.map((document) => <article key={document.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3"><FileText className={files[document.id]?.status === "Uploaded" ? "text-emerald-500" : "text-slate-400"}/><div className="min-w-0 flex-1"><b className="block text-xs uppercase">{document.label}{document.required && <em className="ml-2 not-italic text-[9px] text-rose-500">REQUIRED</em>}</b><span className={`block truncate text-[10px] ${files[document.id]?.status === "Uploaded" ? "text-emerald-600" : "text-slate-400"}`}>{files[document.id]?.name || "Awaiting packaging evidence"}</span></div>{files[document.id]?.status === "Uploaded" && <button onClick={() => removeFile(document.id)} className="text-[10px] font-black uppercase text-rose-500">Remove</button>}<label className="cursor-pointer rounded-lg border bg-slate-50 px-4 py-2 text-[10px] font-black uppercase">{uploading === document.id ? "Uploading..." : files[document.id]?.status === "Uploaded" ? "Replace" : "Upload"}<input className="sr-only" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={(e) => selectFile(document.id, e)}/></label></article>)}</div></div>
      </div><aside className={`overflow-hidden rounded-3xl bg-slate-900 text-white shadow-xl xl:sticky xl:top-24 xl:self-start ${quoteLoading ? "opacity-80" : ""}`}><div className="flex items-center gap-2 border-b border-white/10 p-5 text-blue-400"><Receipt size={16}/><span className="text-[10px] font-black uppercase tracking-[.2em]">Transaction Ledger (INR)</span></div><div className="space-y-5 p-5"><Ledger title="Prepaid Wallet" balance={costs.openingWalletBalance} lines={[["IIP Official Fee", costs.officialFee]]} after={costs.closingWalletBalance}/><Ledger title="Corporate Credit Line" balance={costs.currentCreditLimit} lines={[["Audit Preparation", costs.draftingFee], ["Certification Premium", costs.successPremium], ["GST", costs.gst]]} after={costs.availableCreditAfter}/></div><div className="flex justify-between bg-[#2952ff] p-5"><div><span className="text-[9px] font-black uppercase text-blue-100">Total Audit Debit</span><b className="block text-2xl">₹{Number(costs.total || 0).toLocaleString("en-IN")}</b></div><span className="text-right text-[9px] uppercase text-white/70">SLA: {config?.sla}<br/>{ledger.transactions.length} ledger entries</span></div></aside></div>
      <footer className="flex flex-col justify-between gap-3 border-t bg-slate-50 p-5 sm:flex-row"><button onClick={onBack} className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Discard</button><div className="flex gap-3"><button onClick={saveDraft} disabled={busy} className="flex items-center gap-2 rounded-xl border bg-white px-6 py-3 text-sm font-bold"><Save size={16}/> Save Draft</button><button onClick={submit} disabled={busy || !valid} className={`flex items-center gap-2 rounded-xl px-7 py-3 text-sm font-black ${valid ? "bg-[#2952ff] text-white" : "bg-slate-200 text-slate-400"}`}>{valid ? "Confirm & Submit" : "Incomplete Audit"}<ArrowRight size={16}/></button></div></footer>
    </div></div></div>;
}
function Field({ label, children }) { return <label className="space-y-1.5"><span className="px-1 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">{label}</span><span className="iem-field-control block">{children}</span></label>; }
function Ledger({ title, balance, lines, after }) { return <div><div className="mb-3 flex justify-between text-[10px] font-black uppercase tracking-widest text-slate-500"><span>{title}</span><Wallet size={14}/></div><div className="space-y-2 text-xs"><div className="flex justify-between"><span className="text-slate-400">Opening Balance</span><b>₹{Number(balance || 0).toLocaleString("en-IN")}</b></div>{lines.map(([label, amount]) => <div key={label} className="flex justify-between border-t border-white/10 pt-2"><span className="text-slate-400">{label}</span><b className="text-rose-400">- ₹{Number(amount || 0).toLocaleString("en-IN")}</b></div>)}<div className="flex justify-between border-t border-white/10 pt-2"><span className="text-blue-400">Available Post-Task</span><b>₹{Number(after || 0).toLocaleString("en-IN")}</b></div></div></div>; }
